app/screens/homepage/Homepage.js, app/screens/homepage/search/FlightsSearchOverlay.js, app/screens/homepage/search/LocationSuggestions.js, app/screens/homepage/search/LocationSuggestionsWrapper.js, app/screens/homepage/search/SearchHeader.js, app/screens/homepage/search/SearchHeaderForm.js, app/screens/homepage/search/__generated__/LocationSuggestions.graphql.js, app/screens/homepage/search/__generated__/LocationSuggestionsWrapperQuery.graphql.js, app/src/redux/Store.js, app/src/redux/reducers/SearchReducer.js, app/src/redux/reducers/UserReducer.js, app/types/Redux.js
=> Fetch search location suggestions from API

.flowconfig, .travis.yml, app/components/flights/__generated__/AirlineLogo.graphql.js, app/components/flights/__generated__/Airport.graphql.js, app/components/flights/__generated__/Price.graphql.js, app/components/flights/__generated__/RouteStop.graphql.js, app/screens/bookings/__generated__/AllBookingsListRow_node.graphql.js, app/screens/bookings/__generated__/AllBookingsList_bookings.graphql.js, app/screens/homepage/search/__generated__/LocationSuggestions.graphql.js, app/screens/search/SearchResults.js, app/screens/search/__generated__/SearchResultRow_node.graphql.js, app/screens/search/__generated__/SearchResults_flights.graphql.js, app/scripts/RelayCompiler.js, app/scripts/test.sh, package.json, yarn.lock
The main benefit is that the Flow type are not commented out so the
IDE auto completion works just fine. It case of any problems it's
very easy to revert it - just return original compiler and regenerate
the __generated__ content.
=> Use custom RelayCompiler

app/native/src/components/authentication/Login.js
=> Fix missing key in Login component

app/hotels/src/allHotels/AllHotelsSearchRow.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchRow.graphql.js, schema.graphql
It also updates GraphQL introspection containing schema for hotels.
=> Hotels: add hotel names to the search output

app/hotels/src/SingleHotel.js, app/hotels/src/__generated__/SingleHotelScreenQuery.graphql.js, app/hotels/src/allHotels/AllHotelsSearchRow.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchRow.graphql.js, app/hotels/src/gallery/GalleryGrid.js, schema.graphql
Note that SingleHotel component will be completely rewrited so we
can freely ignore it now...
=> Hotels: use real photos

app/common/src/loaders/FullPageLoading.js, app/common/src/loaders/IconLoading.js
Main inspiration: https://www.kiwi.com/storybook/?selectedKind=Components%2FButton&selectedStory=loading-blue&full=0&down=1&left=1&panelRight=1&downPanel=storybook%2Factions%2Factions-panel (I basically copy pasted the behavior)
=> Add less embarrassing loading indicator

.github/PULL_REQUEST_TEMPLATE.md, README.md
See: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
=> Add pull request template

app/core/src/navigation/HotelsStackNavigator.js
Thanks, @jaroslav-kubicek. I didn't know `@expo/vector-icons`...
=> Navigation: use map icon

app/common/src/cards/SimpleCard.js, app/common/src/cards/__tests__/SimpleCard.test.js, app/common/src/cards/__tests__/__snapshots__/SimpleCard.test.js.snap
=> Refactor 'SimpleCard' padding definition and tests

.flowconfig
Part of the reason why is this failing: https://travis-ci.org/kiwicom/react-native-app/builds/319052937
=> Flow: ignore '.git' folder

app/common/index.js, app/common/src/map/Address.js, app/common/src/map/HotelCard.js, app/common/src/view/VerticalSwipeResponder.js, app/common/types/Events.js
=> Fix flow & eslint issues on master

app/common/index.js, app/common/src/map/DropMarker.js, app/common/src/map/__tests__/DropMarker.test.js, app/common/src/map/__tests__/__snapshots__/DropMarker.test.js.snap
Note: I didn't do the white circle in the middle of marker and I hope
no-one will notice... :)) (I don't know how to do it easily)
Closes #58
Checklist:
=> Hotels map: create "drop" marker component

app/hotels/src/allHotels/AllHotelsSearchList.js, app/hotels/src/allHotels/__tests__/AllHotelsSearchList.test.js, app/hotels/src/allHotels/__tests__/__snapshots__/AllHotelsSearchList.test.js.snap
=> Show an error when all hotels query fails

app/core/src/navigation/HotelsStack.js, app/core/src/navigation/index.js, app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/__generated__/HotelDetailScreen_availableHotel.graphql.js, app/hotels/src/singleHotel/__generated__/singleHotelQuery.graphql.js, app/hotels/src/singleHotel/index.js, app/hotels/src/singleHotel/roomList/RoomList.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/hotels/src/singleHotel/roomList/RoomRowContainer.js, app/hotels/src/singleHotel/roomList/__generated__/RoomList.graphql.js, app/hotels/src/singleHotel/roomList/__generated__/RoomRowContainer_availableRoom.graphql.js, app/hotels/src/singleHotel/roomPicker/NoneSelected.js, app/hotels/src/singleHotel/roomPicker/RoomPicker.js
=> WIP: Simple booking form

app/hotels/src/map/HotelSwipeItem.js, app/hotels/src/map/__tests__/__snapshots__/HotelSwipeItem.js.snap
=> Truncate too long hotel name in swipe card

app/hotels/src/map/MapView.js
=> Do not animate when map is rendered & show better region area

app/hotels/src/allHotels/AllHotels.js, app/hotels/src/allHotels/__tests__/AllHotels.isReadyToSearch.test.js
=> Hotels: fix 'isReadyToSearch' method (must work with zero coordinates)

.env, .flowconfig, README.md, app/common/index.js, app/common/src/WebView.js, app/core/config/application.js, app/core/src/navigation/HotelsStack.js, app/core/src/screens/searchResults/WebBooking.js, app/core/src/types/Navigation.js, app/hotels/index.js, app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/PaymentScreen.js, app/hotels/src/singleHotel/__tests__/PaymentScreen.test.js, app/hotels/src/singleHotel/__tests__/__snapshots__/PaymentScreen.test.js.snap, app/hotels/src/singleHotel/index.js, app/hotels/src/singleHotel/roomList/RoomList.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/hotels/src/singleHotel/roomList/RoomRowContainer.js
=> Hotels: add Payment (whitelabel) page

app/core/src/navigation/HotelsStack.js, app/core/src/screens/hotels/AllHotelsMapNavigationScreen.js, app/core/src/screens/hotels/AllHotelsNavigationScreen.js, app/core/src/services/redux/Store.js, app/core/src/services/redux/reducers/HotelsReducer.js, app/core/src/services/redux/reducers/__tests__/HotelsReducer.test.js, app/core/src/services/redux/reducers/__tests__/__snapshots__/HotelsReducer.test.js.snap, app/core/src/types/Redux.js, app/hotels/src/allHotels/AllHotels.js, app/hotels/src/allHotels/__tests__/AllHotels.isReadyToSearch.test.js, app/hotels/src/allHotels/searchForm/SearchForm.js, app/hotels/src/map/AllHotelsMap.js
Must come after #88 
Checklist:
=> Share filters across screens

.circleci/config.yml
CircleCI is more powerful for our needs but the scripts are not ready yet. So, for now, it will run in parallel with Travis-CI until we fix all related issues.
---
=> Fix build on .circleci

app/hotels/src/filter/stars/StarsCheckbox.js, app/hotels/src/filter/stars/StarsPopup.js, app/hotels/src/filter/stars/__tests__/StarsCheckbox.test.js, app/hotels/src/filter/stars/__tests__/__snapshots__/StarsCheckbox.test.js.snap, app/hotels/src/filter/stars/__tests__/__snapshots__/StarsPopup.test.js.snap
=> Search: hide hotels numbers in stars filter

app/hotels/src/filter/FilterStripe.js, app/hotels/src/filter/price/PriceFilter.js, app/hotels/src/filter/price/PricePopup.js
=> Price filter design

app/common/src/errors/GeneralError.js, app/common/src/errors/__tests__/__snapshots__/GeneralError.test.js.snap, app/core/package.json, app/core/src/navigation/HotelsStack.js, app/core/src/screens/hotels/AllHotelsNavigationScreen.js, app/hotels/src/allHotels/AllHotels.js, app/hotels/src/allHotels/AllHotelsSearchRow.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchRow.graphql.js, app/hotels/src/singleHotel/__generated__/singleHotelQuery.graphql.js, app/hotels/src/singleHotel/description/Description.js, app/hotels/src/singleHotel/description/DescriptionContainer.js, app/hotels/src/singleHotel/description/__generated__/DescriptionContainer_hotel.graphql.js, app/hotels/src/singleHotel/index.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/relay/src/QueryRenderer.js, yarn.lock
Also, closes #106
I will probably need to refactor it - my brain hurts. However, I would appreciate quick CR. Basically, single hotel page should now load correct hotel. I had to fix all related issues with single hotel page because it was broken...
---
=> Hotels: connect single hotel page to the real data

android/app/build.gradle, android/app/src/main/java/com/reactnativeapp/MainApplication.java, android/settings.gradle, app/common/package.json, app/common/src/loaders/IconLoading.js, ios/Podfile, yarn.lock
=> Add react-native-svg

app/hotels/src/HotelsReducer.js, app/hotels/src/__tests__/HotelsReducer.test.js, app/hotels/src/__tests__/__snapshots__/HotelsReducer.test.js.snap, app/hotels/src/allHotels/AllHotels.js, app/hotels/src/allHotels/AllHotelsSearch.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__tests__/AllHotels.isReadyToSearch.test.js, app/hotels/src/allHotels/searchForm/SearchForm.js, app/hotels/src/allHotels/searchForm/SearchParametersType.js, app/hotels/src/filter/FilterParametersType.js, app/hotels/src/filter/FilterStripe.js, app/hotels/src/filter/price/PriceFilter.js, app/hotels/src/filter/price/PricePopup.js, app/hotels/src/filter/stars/StarsFilter.js, app/hotels/src/map/AllHotelsMap.js, app/hotels/src/map/__generated__/AllHotelsMapQuery.graphql.js, app/hotels/src/navigation/AllHotelsMapNavigationScreen.js, app/hotels/src/navigation/AllHotelsNavigationScreen.js
=> Connect price filter

app/hotels/src/HotelsReducer.js, app/hotels/src/allHotels/AllHotelsSearch.js
This issue has been resolved in GraphQL.
---
=> Hotels: remove minimal string length for city search

app/hotels/src/allHotels/AllHotels.js, app/hotels/src/map/AllHotelsMap.js, app/hotels/src/map/HotelSwipeItem.js, app/hotels/src/map/HotelSwipeList.js, app/hotels/src/map/MapScreen.js, app/hotels/src/map/__generated__/AllHotelsMapQuery.graphql.js, app/hotels/src/map/__generated__/HotelSwipeItem.graphql.js, app/hotels/src/map/__tests__/HotelSwipeItem.test.js, app/hotels/src/map/__tests__/__snapshots__/HotelSwipeItem.test.js.snap, app/hotels/src/navigation/AllHotelsMapNavigationScreen.js, app/hotels/src/singleHotel/index.js
=> Enable navigating to single hotel detail from map view

app/hotels/src/map/Address.js, app/hotels/src/map/HotelSwipeItem.js, app/hotels/src/map/__tests__/__snapshots__/HotelSwipeItem.test.js.snap
=> UX improvements in map view according to design specs

app/hotels/src/HotelsReducer.js, app/hotels/src/__tests__/HotelsReducer.test.js, app/hotels/src/__tests__/__snapshots__/HotelsReducer.test.js.snap, app/hotels/src/allHotels/__tests__/AllHotels.isReadyToSearch.test.js, app/hotels/src/filter/FilterParametersType.js, app/hotels/src/filter/FilterStripe.js, app/hotels/src/filter/stars/StarsFilter.js, app/hotels/src/filter/stars/StarsPopup.js, app/hotels/src/filter/stars/__tests__/StarsPopup.test.js, app/hotels/src/filter/stars/__tests__/__snapshots__/StarsPopup.test.js.snap
Closes #124 
**Merge #139 first.**
---
=> Connect rating filter

app/hotels/src/singleHotel/galleryButton/GalleryButton.js, app/hotels/src/singleHotel/header/Header.js, app/hotels/src/singleHotel/header/__tests__/__snapshots__/Header.test.js.snap
=> Make whole gallery image clickable

app/hotels/src/map/HotelSwipeList.js
=> Limit the width of the swipe list

app/common/index.js, app/common/src/errors/ErrorMessage.js, app/hotels/src/allHotels/AllHotelsSearch.js, app/hotels/src/allHotels/searchForm/SearchForm.js, app/hotels/src/allHotels/searchForm/__tests__/__snapshots__/SearchForm.test.js.snap
=> Fix date range

app/hotels/src/allHotels/HotelReviewScore.js, app/hotels/src/allHotels/__tests__/HotelReviewScore.test.js
=> Hotels: hide falsy hotel score (instead of '0.0')

app/common/src/view/VerticalSwipeResponder.js, app/hotels/src/map/HotelSwipeList.js
=> Use animation when showing/hiding address in map view

.gitignore, README.md, app/hotels/README.md, app/hotels/index.js, package.json, scripts/build.sh
This is necessary to be able to build, distribute and use these builds
in the native code.
---
=> Register hotels package to the 'AppRegistry'

app/hotels/src/map/AllHotelsMap.js, app/hotels/src/map/MapScreen.js
=> Add filter stripe to map view

app/core/src/navigation/index.js, app/hotels/src/allHotels/AllHotels.js, app/hotels/src/allHotels/AllHotelsSearch.js, app/hotels/src/allHotels/__generated__/AllHotelsQuery.graphql.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__tests__/AllHotels.isReadyToSearch.test.js, app/hotels/src/filter/FilterStripe.js, app/hotels/src/map/AllHotelsMap.js, app/hotels/src/map/__generated__/AllHotelsMapQuery.graphql.js, app/hotels/src/navigation/AllHotelsMapNavigationScreen.js, app/hotels/src/navigation/AllHotelsNavigationScreen.js, app/hotels/src/navigation/NavigationStack.js, app/hotels/src/singleHotel/__generated__/singleHotelQuery.graphql.js, app/hotels/src/singleHotel/index.js, schema.graphql
Uses `currency` prop passed to `HotelsStandalonePackage` to show prices in that specific currency.
---
=> Use currency prop in all relevant queries

.jest.json, app/common/src/services/Logger.js, app/common/src/services/__tests__/Logger.test.js, app/common/src/services/__tests__/__snapshots__/Logger.test.js.snap, app/core/config/jestSetup.js, app/hotels/src/allHotels/AllHotelsSearchList.js, app/hotels/src/allHotels/searchForm/SearchForm.js, app/hotels/src/singleHotel/HotelDetailScreen.js
Note - we do not have information about `hasActiveBooking`.
See: https://confluence.kiwi.com/display/MOB/Semi+native+hotels#Seminativehotels-Logging
---
=> Log real events in hotels package

app/common/src/popup/BarPopup.js, app/common/src/popup/ButtonPopup.js, app/common/src/popup/Popup.js, app/common/src/popup/__tests__/__snapshots__/ButtonPopup.test.js.snap, app/hotels/src/filter/price/PricePopup.js
=> Use ScrollView only when it's needed

app/common/src/Price.js
The only problem is that I don't really know how the formatter works
because there are not enough details in the specification.
See: https://confluence.kiwi.com/display/MOB/Semi+native+hotels#Seminativehotels-Currencyratesandformatters
---
=> Use CurrencyFormatter in Price component

app/hotels/package.json, yarn.lock
=> Fix missing dependency on querystring

app/hotels/src/allHotels/HotelDistance.js, app/hotels/src/allHotels/HotelTitle.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__generated__/HotelDistance_hotel.graphql.js, app/hotels/src/allHotels/__generated__/HotelTitle.graphql.js, app/hotels/src/allHotels/__tests__/HotelDistance.test.js, schema.graphql
**Merge after [Gitlab 591]**
---
=> Show distance from city center in hotel results

app/hotels/src/filter/price/PricePopup.js, app/shared/src/popup/BarPopup.js, app/shared/src/popup/ButtonPopup.js, app/shared/src/popup/Popup.js, app/shared/src/popup/__tests__/__snapshots__/ButtonPopup.test.js.snap
=> Pop scrollable only when needed

app/hotels/src/allHotels/searchForm/guests/GuestsPopup.js, app/hotels/src/allHotels/searchForm/guests/__tests__/GuestsPopup.test.js, app/hotels/src/allHotels/searchForm/guests/__tests__/__snapshots__/GuestsPopup.test.js.snap
=> Close guests popup on save

app/hotels/src/allHotels/searchForm/DateInput.js
=> Set max dates for date pickers

app/shared/src/buttons/IncrementDecrementButtons.js
=> Reduce line height for android decrement-increment buttons

app/shared/src/buttons/LinkButton.js, app/shared/src/popup/BarPopup.js
=> Add padding to BarPopup link buttons

app/hotels/src/filter/FilterButton.js, app/hotels/src/filter/__tests__/__snapshots__/FilterButton.test.js.snap
=> Add background color to filter button wrapper

app/hotels/src/map/singleHotel/BottomSheet.js
=> Align bottom sheet to center

app/shared/src/map/DropMarker.js
=> Make marker visible on android

app/shared/src/bottomSheet/BottomSheet.js
=> Add rounded corners and elevation

app/hotels/src/allHotels/searchForm/guests/GuestsPopup.js, app/hotels/src/allHotels/searchForm/guests/__tests__/__snapshots__/GuestsPopup.test.js.snap
=> Allow close on click outside with error

app/hotels/src/allHotels/searchForm/guests/GuestsPopup.js, app/hotels/src/allHotels/searchForm/guests/__tests__/GuestsPopup.test.js
=> Remove error message when children is set to 0

android/app/src/main/java/com/reactnativeapp/MainApplication.java, app/core/config/NativeModulesMocks/RNTranslationManager.js, app/core/config/jestSetup.js, app/shared/index.js, app/shared/src/translations/Translate.js, app/shared/src/translations/__tests__/Translate.test.js, ios/Podfile
=> Use native translations

app/hotels/src/allHotels/searchForm/guests/GuestsPopup.js, app/hotels/src/allHotels/searchForm/guests/__tests__/GuestsPopup.test.js, app/hotels/src/allHotels/searchForm/guests/__tests__/__snapshots__/GuestsPopup.test.js.snap
=> Fix guests popup children set age bug

README.md, android/app/src/main/java/com/reactnativeapp/MainApplication.java, app/core/config/NativeModulesMocks/RNColors.js, app/core/config/jestSetup.js, app/hotels/src/allHotels/searchForm/__tests__/__snapshots__/SearchForm.test.js.snap, app/hotels/src/filter/__tests__/__snapshots__/FilterButton.test.js.snap, app/hotels/src/filter/stars/__tests__/__snapshots__/StarsCheckbox.test.js.snap, app/hotels/src/singleHotel/bookNow/__tests__/__snapshots__/BookNow.test.js.snap, app/shared/package.json, app/shared/src/Color.js, app/shared/src/buttons/__tests__/__snapshots__/Button.test.js.snap, app/shared/src/map/__tests__/__snapshots__/DropMarker.test.js.snap, ios/Podfile, ios/SampleView.m, package.json, scripts/podInstall.js, yarn.lock
=> Use native colors

README.md
=> Add documentation for native modules

rn-cli.config.js
=> Add build package.json to blacklist

android/app/src/main/java/com/reactnativeapp/MainApplication.java, app/shared/package.json, yarn.lock
=> Upgrade @kiwicom/react-native-native-modules

app/hotels/src/navigation/AllHotelsNavigationScreen.js, app/shared/index.js, app/shared/src/DismissKeyboardView.js
=> Add keyboard dismiss view around hotels search

app/hotels/src/singleHotel/location/Location.js
=> Set mini map not scrollable

app/shared/src/popup/Popup.js
=> Have back button close modals

app/hotels/src/singleHotel/roomPicker/RoomPicker.js
=> Add more padding to RoomPicker

app/hotels/src/navigation/NavigationStack.js
=> Add title to webview screen

app/hotels/src/singleHotel/bookNow/BookNow.js, app/hotels/src/singleHotel/bookNow/__tests__/__snapshots__/BookNow.test.js.snap, app/hotels/src/singleHotel/roomPicker/NoneSelected.js, app/shared/index.js, app/shared/src/buttons/Button.js, app/shared/src/buttons/ButtonText.js, app/shared/src/buttons/LinkButton.js, app/shared/src/buttons/__tests__/ButtonText.test.js, app/shared/src/buttons/__tests__/__snapshots__/Button.test.js.snap, app/shared/src/buttons/__tests__/__snapshots__/ButtonText.test.js.snap
=> Uppercase button text on android

app/hotels/src/allHotels/searchForm/guests/Guests.js, app/hotels/src/allHotels/searchForm/guests/__tests__/Guests.ButtonTitle.test.js, app/hotels/src/allHotels/searchForm/guests/__tests__/__snapshots__/Guests.ButtonTitle.test.js.snap, app/hotels/src/allHotels/searchForm/guests/__tests__/__snapshots__/Guests.test.js.snap
See: https://trello.com/c/TYCGDaYg/129-bug-date-pickers-are-not-optimized-for-small-devices
=> Hotels: add children count to the guests button

app/hotels/src/allHotels/searchForm/DateInput.js, app/hotels/src/allHotels/searchForm/guests/Guests.js, app/hotels/src/allHotels/searchForm/guests/__tests__/__snapshots__/Guests.test.js.snap, app/shared/src/forms/DatePicker.js
See: https://trello.com/c/TYCGDaYg/129-bug-date-pickers-are-not-optimized-for-small-devices
Note: I am not using correct icons because I need to update Icon
component first. This change will follow.
=> Hotels: add styles to the search datepickers

app/hotels/src/singleHotel/AvailableHotelSearchInput.js, app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/__generated__/singleHotelQuery.graphql.js, app/hotels/src/singleHotel/bookNow/BookNow.js, app/hotels/src/singleHotel/bookNow/BookNowText.js, app/hotels/src/singleHotel/bookNow/__tests__/BookNow.test.js, app/hotels/src/singleHotel/bookNow/__tests__/__snapshots__/BookNow.test.js.snap, app/hotels/src/singleHotel/index.js, app/hotels/src/singleHotel/roomList/RoomList.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/hotels/src/singleHotel/roomList/__generated__/RoomRow_availableRoom.graphql.js
=> Show persons and rooms on book now button

app/hotels/src/map/HotelDetailPreview.js
=> Adjust hotel detail preview styling

app/hotels/src/map/allHotels/PriceMarker.js, app/shared/package.json, app/shared/src/Price.js, app/shared/src/__tests__/Price.test.js, app/shared/src/__tests__/__snapshots__/Price.test.js.snap, app/shared/src/currency/CurrencyFormatter.js, app/shared/src/currency/__tests__/CurrencyFormatter.test.js, yarn.lock
=> Update price component and currency formatter

app/shared/src/forms/AgePicker.js, app/shared/src/popup/BarPopup.js
=> Adjust side padding on age pop up

app/hotels/src/singleHotel/HotelDetailScreen.js
Book Now button wasn't able to spread across the whole screen (on
tables) because of restrictions we introduce in the Layout component.
=> Fix "Book Now" button

app/config/package.json, app/hotels/package.json, app/redux/package.json, app/relay/package.json, app/shared/package.json
We are not deploying them to NPM so they should be private.
=> Make all packages private by default

app/hotels/src/allHotels/AllHotels.js
=> Pass currency correctly all the way to AllHotelsSearch

app/hotels/src/singleHotel/PaymentScreen.js, app/hotels/src/singleHotel/__tests__/__snapshots__/PaymentScreen.test.js.snap
See: https://trello.com/c/ulX4a98Z/213-minor-change-modify-label-parameter-in-bookingcom-url-so-we-could-properly-evaluate-ab-test
=> Hotels: update 'label' parameter of the payment URL for AB testing

app/hotels/src/singleHotel/roomList/RoomRowTitle.js
=> Hide room size if null

app/hotels/src/allHotels/AllHotelsSearchList.js, app/hotels/src/allHotels/LoadMoreButton.js, app/hotels/src/allHotels/__tests__/LoadMoreButton.test.js, app/hotels/src/allHotels/__tests__/__snapshots__/AllHotelsSearchList.test.js.snap, app/hotels/src/allHotels/__tests__/__snapshots__/LoadMoreButton.test.js.snap
Closes https://github.com/kiwicom/react-native-app/issues/379
=> Hotels: fix styles of "Load More" button

android/app/build.gradle, android/app/src/main/java/com/reactnativeapp/MainActivity.java
=> Update to logging library 0.2.1

app/hotels/src/singleHotel/roomList/RoomRowTitle.js
It worked before I introduced translations.
=> Hotels: fix &nbsp; entity in RoomRowTitle

app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/__generated__/singleHotelQuery.graphql.js, app/hotels/src/singleHotel/galleryButton/GalleryButton.js, app/hotels/src/singleHotel/roomList/RoomImage.js, app/hotels/src/singleHotel/roomList/RoomList.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/hotels/src/singleHotel/roomList/__generated__/RoomRow_availableRoom.graphql.js, app/hotels/src/singleHotel/roomList/__tests__/RoomRow.test.js
=> Add room detail gallery

.eslintrc.js, app/core/src/navigation/HomepageStack.js, app/core/src/navigation/index.js, app/hotels/src/navigation/AllHotelsNavigationScreen.js, app/hotels/src/navigation/NavigationStack.js, app/navigation/index.js, app/navigation/package.json, app/translations/src/DefaultVocabulary.js
Closes: https://github.com/kiwicom/react-native-app/issues/285
Now we just need to prepare Phraseapp deployment.
=> Translate all navigation titles

app/hotels/src/singleHotel/index.js, app/translations/index.js, app/translations/src/MapLocaleToLanguageQuery.js, app/translations/src/__tests__/MapLocaleToLanguageQuery.test.js
=> Map language locales to booking.com language

app/core/config/jestSetup.js, app/translations/package.json, yarn.lock
=> Remove 'react-native-device-info' dependency

app/hotels/index.js, app/hotels/src/allHotels/AllHotels.js, app/hotels/src/gallery/GalleryGrid.js, app/hotels/src/map/allHotels/HotelSwipeList.js, app/hotels/src/map/singleHotel/BottomSheet.js, app/hotels/src/singleHotel/hotelInformation/description/Description.js, app/shared/src/forms/DatePicker.js, app/shared/src/popup/Popup.js
I left tests out of it, and `Translations` there were some tests failing when I used StyleSheet in translations, saying create is undefined. Probably circular references?
=> Remove inline styles

app/hotels/src/navigation/NavigationStack.js, app/hotels/src/singleHotel/header/Header.js, app/navigation/index.js
@tbergq I am not really confident about the implementation. I had to combine 3 designs... 😢
=> Single hotel page: make navigation header transparent on Android

.eslintrc.js, app/hotels/src/filter/score/ScorePopup.js, app/hotels/src/navigation/GuestsModalScreen.js, app/hotels/src/navigation/LocationPickerScreen.js, app/shared/src/forms/Slider.js
See: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md
=> Eslint: enable 'react/jsx-boolean-value' rule

app/playground/Playground.js, app/shared/src/forms/DatePicker.js, app/shared/src/forms/__tests__/__snapshots__/DatePicker.test.js.snap
Datepicker confirm and cancel button had disappeared due to too much paddingVertical
=> Fix datepicker button styling

schema.graphql
Format of GraphQL comments is changed due to Relay upgrade (Relay now
understand this new format).
=> Upgrade GraphQL schema

app/hotels/src/filter/price/PriceFilter.js
=> Have pricefilter always use Euro

app/shared/src/view/VerticalSwipeResponder.js
=> Refactor unsafe_componentWillReceiveProps method

app/hotels/package.json, app/hotels/src/singleHotel/PaymentScreen.js, app/hotels/src/singleHotel/__tests__/PaymentScreen.test.js, app/hotels/src/singleHotel/__tests__/__snapshots__/PaymentScreen.test.js.snap, scripts/releaseHotels.js
=> Add version to payment screen label

app/hotels/src/allHotels/searchForm/guests/GuestsModal.js, app/hotels/src/navigation/allHotels/GuestsModalScreen.js, app/hotels/src/navigation/allHotels/__tests__/GuestsModalScreen.test.js, app/hotels/src/navigation/allHotels/__tests__/__snapshots__/GuestsModalScreen.test.js.snap
Moving some parts of the view from`GuestsModalScreen` to `GuestsModal`
We can not push all logic down since the save button is located in the header of `GuestsModalScreen` and when that is pressed, this component needs to know if it should save or show error.
=> Refactor guests modal

.build/package.json, package.json, yarn.lock
=> Upgrade react native version

app/hotels/src/allHotels/searchForm/guests/Guests.js, app/hotels/src/allHotels/searchForm/guests/__tests__/__snapshots__/Guests.ButtonTitle.test.js.snap
See [Trello](https://trello.com/c/mS3A1SHz/249-bug-after-selecting-children-it-appears-in-grey-color-and-adults-are-in-black)
Not sure if this is a bug or not. If it is a bug, this will fix it. If not, just close the pull request.
=> Show children with black text when children are selected

app/core/src/navigation/index.js
Basically the idea is to get closer and closer to the final application.
=> Add TabNavigator to the core package

app/relay/src/Environment.js, app/relay/src/__tests__/Environment.test.js
=> Fix no partial error shown bug

app/hotels/src/allHotels/AllHotels.js, app/hotels/src/allHotels/AllHotelsSearch.js, app/hotels/src/allHotels/AllHotelsSearchList.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchListQuery.graphql.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchList_data.graphql.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__tests__/AllHotelsSearchList.test.js, app/hotels/src/map/allHotels/AllHotelsMap.js, app/hotels/src/search/SearchQueryHelpers.js, app/hotels/src/search/__tests__/SearchQueryHelpers.test.js, schema.graphql
=> Show cityName from allHotelsQuery when available

app/hotels/src/navigation/allHotels/__tests__/GuestsModalScreen.test.js, app/localization/src/__tests__/Translation.test.js
=> Make tests that render translations async

app/MMB/src/RightMenu.js, app/MMB/src/components/MenuGroup.js, app/MMB/src/components/MenuItem.js, app/MMB/src/navigation/MMBScreen.js
Just a design at this moment (it's not clickable).
=> MMB: create MenuItem and MenuGroup components

app/MMB/src/HelpSubmenu.js, app/MMB/src/MainMenu.js, app/MMB/src/OtherSubmenu.js, app/MMB/src/components/menu/MenuGroup.js, app/MMB/src/components/menu/MenuItem.js, app/MMB/src/components/menu/TitledMenuGroup.js, app/MMB/src/navigation/MMBScreen.js, app/localization/src/DefaultVocabulary.js
I prepared every submenu of the "Manage" group in the main menu. It
should be fine from the design point of view but it's not clickable yet.
This logic will follow...
=> MMB: introduce new 'TitledMenuGroup' component

app/MMB/src/appRegistry/ManageMyBookingPackage.js, app/MMB/src/list/Flights.js, app/MMB/src/navigation/MMBListScreen.js, app/MMB/src/navigation/MMBScreen.js, app/core/src/components/relay/PrivateApiRenderer.js, app/core/src/screens/MMBPackageWrapper.js, app/relay/index.js, app/relay/src/AuthContext.js, app/relay/src/PrivateApiRenderer.js, app/relay/src/__tests__/AuthContext.test.js
=> Add accessToken to context

.flowconfig, app/config/ConfigContext.js, app/config/index.js, app/localization/src/DateFormatter.js, app/localization/src/DefaultVocabulary.js, app/localization/src/GetDeviceLocale.js, app/localization/src/transformations/CaseTransform.js, app/localization/src/transformations/__tests__/CaseTransform.test.js, app/shared/src/AppStateChange.js, app/shared/src/Color.js, app/shared/src/Device.js, app/shared/src/GeolocationContext.js, app/shared/src/LayoutAnimation.js, app/shared/src/currency/CurrencyFormatter.js, app/shared/types/Styles.js, rn-cli.config.js, scripts/activatePlayground.js, scripts/configureApplication.js, scripts/getSchema.js, scripts/podInstall.js, scripts/releaseHotels.js
Strict mode it's not used everywhere (only where it's without big
problems). I would like to try it at least. It's super easy to revert it
but we should try to push it instead...
=> Flow: use strict mode

app/MMB/package.json, app/MMB/src/menu/Invoice.js, app/MMB/src/menu/OtherSubmenu.js, app/MMB/src/menu/__generated__/InvoiceQuery.graphql.js, app/MMB/src/navigation/DetailScreen.js, app/localization/src/DefaultVocabulary.js, app/navigation/index.js, app/navigation/types/Navigation.js
Detail screen is now connected to the real booking ID and everything in
"Other" section should be finished.
=> MMB: complete "Other" menu

app/MMB/src/menu/HelpSubmenu.js, app/MMB/src/navigation/DetailScreen.js, app/navigation/types/Navigation.js, scripts/configureApplication.js
To do: "Call support" screen - API is not ready for this.
=> MMB: add "Help" screen

app/shared/package.json, app/shared/src/forms/__tests__/__snapshots__/Slider.test.js.snap, yarn.lock
=> Dependencies: upgrade multi-slider to the latest version (^0.0.14)

app/MMB/src/list/cityImage/CityImage.js
=> Fix rounded corners on cityImage android

app/MMB/src/MainMenu.js, app/MMB/src/components/header/Header.js, app/MMB/src/components/header/StatusBar.js, app/MMB/src/components/header/StatusBarIcon.js, app/MMB/src/components/header/TripInfo.js, app/MMB/src/components/header/__generated__/HeaderQuery.graphql.js, app/MMB/src/components/header/__generated__/StatusBar.graphql.js, app/MMB/src/components/header/__generated__/StatusBarIcon.graphql.js, app/MMB/src/components/header/__generated__/TripInfo.graphql.js, app/MMB/src/navigation/DetailScreen.js, app/shared/src/Color.js
Note: it's not ready yet but I feel it's getting big so let's merge this
first part.
=> MMB: create simple trip info components (header)

app/MMB/src/components/header/RouteStop.js, app/MMB/src/components/header/TripInfo.js, app/MMB/src/components/header/TripInfoMulticity.js, app/MMB/src/components/header/TripInfoOneWay.js, app/MMB/src/components/header/TripInfoReturn.js, app/MMB/src/components/header/__generated__/HeaderQuery.graphql.js, app/MMB/src/components/header/__generated__/RouteStop.graphql.js, app/MMB/src/components/header/__generated__/TripInfo.graphql.js, app/MMB/src/components/header/__generated__/TripInfoMulticity.graphql.js, app/MMB/src/components/header/__generated__/TripInfoOneWay.graphql.js, app/MMB/src/components/header/__generated__/TripInfoReturn.graphql.js
Note: it's ready to be merged but it will change a lot in the future.
=> MMB header: add base components for ONE_WAY, RETURN and MULTICITY modes

app/MMB/src/navigation/DetailScreen.js, app/MMB/src/scenes/flightServices/__generated__/FlightServicesMenuGroup_bookedServices.graphql.js, app/MMB/src/scenes/passenger/PassengerDetail.js, app/MMB/src/scenes/passenger/PassengerDetailContainer.js, app/MMB/src/scenes/passenger/__generated__/PassengerDetailContainerQuery.graphql.js, app/MMB/src/scenes/passenger/__generated__/PassengerDetailQuery.graphql.js, app/MMB/src/scenes/passenger/__generated__/PassengerDetail_booking.graphql.js, schema.graphql
Not finished yet, but merging now to keep it small
=> MMB: Add passenger detail page with refetch container

app/MMB/package.json, app/MMB/src/scenes/passenger/Passenger.js, app/MMB/src/scenes/passenger/PassengerDetail.js, app/MMB/src/scenes/passenger/__generated__/PassengerDetailContainerQuery.graphql.js, app/MMB/src/scenes/passenger/__generated__/PassengerDetailQuery.graphql.js, app/MMB/src/scenes/passenger/__generated__/PassengerDetail_booking.graphql.js, app/MMB/src/scenes/passenger/__generated__/Passenger_passenger.graphql.js, app/MMB/src/scenes/passenger/__tests__/Passenger.test.js, app/MMB/src/scenes/passenger/__tests__/__snapshots__/Passenger.test.js.snap, app/localization/src/vocabularies/ManageMyBooking.js, app/playground/src/PlaygroundImports.js, schema.graphql, yarn.lock
Adding another piece of the puzzle, still work to be done
=> MMB: Add passenger name, nationality, date of birth on passenger card

app/MMB/src/scenes/passenger/Passenger.js, app/hotels/src/allHotels/AllHotelsSearchRow.js, app/hotels/src/singleHotel/hotelInformation/description/Description.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/shared/src/cards/SimpleCard.js
=> Refactor simple card style prop

app/MMB/src/components/header/DateTime.js, app/MMB/src/components/header/TripInfoMulticity.js, app/MMB/src/components/header/TripInfoOneWay.js, app/MMB/src/components/header/TripInfoReturn.js, app/MMB/src/components/header/TripTimes.js, app/MMB/src/components/header/__generated__/DateTime.graphql.js, app/MMB/src/components/header/__generated__/HeaderQuery.graphql.js, app/MMB/src/components/header/__generated__/TripInfoMulticity.graphql.js, app/MMB/src/components/header/__generated__/TripInfoOneWay.graphql.js, app/MMB/src/components/header/__generated__/TripTimes.graphql.js, app/localization/src/vocabularies/ManageMyBooking.js
Note: trip duration is missing in GraphQL at this moment
=> MMB header: add 'TripTimes' component

app/localization/package.json, app/localization/src/DateFormatter.js, yarn.lock
=> DateFormatter: add Intl polyfill

ios/reactNativeApp.xcodeproj/project.pbxproj
We removed them unintentionally, we need them.
=> fix: add iOS necessary build phases

ios/RNKiwiMobile/RNKiwiViewControllerFlowDelegate.h, ios/RNNativePlayground/Base.lproj/Main.storyboard, ios/RNNativePlayground/ViewController.m, ios/reactNativeApp.xcodeproj/project.pbxproj
=> Connect swiping solution into rn playground

app/MMB/src/scenes/flightServices/FlightServicesMenuGroup.js
=> MMB: Fix raw text bug on flight services

README.md
I didn't see this error for a long time. Did you? I would prefer to clean it if not...
=> README: remove Troubleshooting section

android/app/src/main/java/com/reactnativeapp/MainApplication.java
Without this change, the application will not run on our test device in debug mode 🤷‍♂️
=> Android: have MainApplication extend MultiDexApplication

app/MMB/src/components/header/StatusBarIcon.js, app/MMB/src/components/header/__generated__/HeaderQuery.graphql.js, app/MMB/src/scenes/list/__generated__/FlightListContainerQuery.graphql.js, app/MMB/src/scenes/list/__generated__/FlightsQuery.graphql.js, app/MMB/src/scenes/list/cityImage/CityImage.js, app/MMB/src/scenes/list/cityImage/ImageBadges.js, app/MMB/src/scenes/list/cityImage/__generated__/CityImage_image.graphql.js, app/MMB/src/scenes/list/cityImage/__generated__/ImageBadges.graphql.js, packages/localization/src/vocabularies/ManageMyBooking.js
=> MMB: Display travelled for past trips with status confirmed

app/MMB/src/MainMenu.js, app/MMB/src/__generated__/MainMenuQuery.graphql.js, app/MMB/src/components/header/Header.js, app/MMB/src/components/header/__generated__/Header.graphql.js
We will also need to fetch data to show passengers below the passenger menu.
It also eliminates the annoying jumping after header loads.
=> MMB: Move QueryRenderer from Header to MainMenu

app/MMB/src/MainMenu.js, app/MMB/src/menuGroups/TripInfoMenuGroup.js, app/MMB/src/navigation/DetailScreen.js, packages/localization/src/vocabularies/ManageMyBooking.js
=> MMB: Add trip info menu group on landing screen

app/MMB/src/scenes/tripServices/InsuranceMenuItem.js, app/MMB/src/scenes/tripServices/TripServices.js, packages/localization/src/vocabularies/ManageMyBooking.js
We need to update GraphQL now because there are conditions to display
this item.
=> MMB: add insurance menu item

app/MMB/src/components/ShareButton.js, app/MMB/src/navigation/DetailScreen.js, app/MMB/src/navigation/DetailShareButton.js
Separate logic from styling so I can re use it for other parts of the app
=> MMB: Refactor share button

README.md
=> Updated README with run instructions for Linux

app/MMB/src/__generated__/MainMenuContainerQuery.graphql.js, app/MMB/src/scenes/tripOverview/MulticityTimeline.js, app/MMB/src/scenes/tripOverview/OneWayTimeline.js, app/MMB/src/scenes/tripOverview/ReturnTimeline.js, app/MMB/src/scenes/tripOverview/Timeline.js, app/MMB/src/scenes/tripOverview/TripOverview.js, app/MMB/src/scenes/tripOverview/__generated__/MulticityTimeline.graphql.js, app/MMB/src/scenes/tripOverview/__generated__/OneWayTimeline.graphql.js, app/MMB/src/scenes/tripOverview/__generated__/ReturnTimeline.graphql.js, app/MMB/src/scenes/tripOverview/__generated__/TripOverview.graphql.js, app/MMB/src/scenes/tripOverview/__generated__/TripOverviewTabletQuery.graphql.js
Just a simple skeleton so I can expand on this idea.
=> MMB: add flight overview timeline

ios/Podfile
=> Fix targets names

app/hotels/src/allHotels/searchForm/locationPicker/LocationPicker.js, app/profile/components/authentication/EmailLoginForm.js, packages/shared/src/Text.js, packages/shared/src/forms/TextInput.js
This also fixes the weird placeholder behavior.
=> Shared: cleanup TextInput component

package.json, scripts/test.sh
This is useful to see unused suppress comments.
=> Flow: always display warnings

scripts/releaseFramework.js
- Do not create the Github tag/release if the framework is not correctly built
- Show output in console
=> Improve iOS release script

.github/CODEOWNERS
@ferrannp Are you OK with this?
=> CODEOWNERS: add @ferrannp as a code owner of Android and iOS code

ios/reactNativeApp.xcodeproj/project.pbxproj
Lowered deployment target for RNKiwiMobile target to iOS9.
=> Add support for iOS9

ios/RNNativePlayground/Info.plist, ios/reactNativeApp.xcodeproj/project.pbxproj
=> Fix fonts for iOS native playground

RNAndroidPlayground/dependencies.gradle, android/app/src/main/java/com/reactnativeapp/MainApplication.java, android/build.gradle, android/dependencies.gradle, android/settings.gradle, packages/shared/package.json, yarn.lock
=> Remove react-native-native-modules dependency

.build/package.json, RNAndroidPlayground/README.md, RNAndroidPlayground/build.gradle, RNAndroidPlayground/dependencies.gradle, RNAndroidPlayground/react-native-maps/build.gradle, RNAndroidPlayground/react-native-native-modules/build.gradle, RNAndroidPlayground/react-native-tooltips/build.gradle, RNAndroidPlayground/react-native-vector-icons/build.gradle, RNAndroidPlayground/rnkiwimobile/build.gradle, RNAndroidPlayground/settings.gradle, package.json, scripts/buildAndroidSnapshots.js, yarn.lock
Fixes #740.
- Generates dependencies SNAPSHOTS(s) taking version from package.json if they do not exist
- Generates JS and `rnkiwmobile` library taking version from package.json if it does note xist
=> Circle CI to build Android dependencies and rnkiwimobile

app/MMB/src/components/header/Header.js, app/MMB/src/components/header/MobileTripOverviewHandle.js
Note: the styles will require some more tweaking to align the icons
properly
=> MMB: add new 'MobileTripOverviewHandle' component

scripts/buildAndroidSnapshots.js
- Native dependencies will only be deployed when the version has changed in `package.json`
- `rnkiwimobile` will be deployed by every merge into `master`
=> Android: Deploy rnkiwimobile for every merge into master

.github/CODEOWNERS
I am opting out of being a code owner since I am moving to another project.
=> Remove @mrtnzlml from the code owners

app/MMB/src/scenes/timeline/MainContentNote.js, app/MMB/src/scenes/timeline/Timeline.js, app/MMB/src/scenes/timeline/TimelineEventIcon.js, app/MMB/src/scenes/timeline/__generated__/TimelineQuery.graphql.js, app/MMB/src/scenes/timeline/events/ArrivalTimelineEvent.js, app/MMB/src/scenes/timeline/events/BoardingTimelineEvent.js, app/MMB/src/scenes/timeline/events/DepartureTimelineEvent/DepartureTimelineEventNote.js, app/MMB/src/scenes/timeline/events/DepartureTimelineEvent/__generated__/DepartureTimelineEvent.graphql.js, app/MMB/src/scenes/timeline/events/DepartureTimelineEvent/index.js, app/MMB/src/scenes/timeline/events/DownloadInvoiceTimelineEvent.js, app/MMB/src/scenes/timeline/events/LeaveForAirportTimelineEvent.js, app/MMB/src/scenes/timeline/events/__generated__/ArrivalTimelineEvent.graphql.js, packages/localization/src/vocabularies/ManageMyBooking.js
And correcting icons style, now that I can run it on iOS
=> Adding Departure and Arrival

app/hotels/src/filter/hotelFacilities/HotelFacilitiesPopup.js, packages/localization/src/vocabularies/Hotels.js, packages/shared/src/popup/Popup.js
=> Hotels: Facilities translations and set pop-up max height

app/hotels/src/gallery/GalleryGrid.js, app/hotels/src/singleHotel/roomList/RoomImage.js
=> Hotels: Disable room gallery when images are missing

app/hotels/src/gallery/GalleryGrid.js, app/hotels/src/navigation/singleHotel/SingleHotelStack.js, app/hotels/src/singleHotel/header/Header.js
=> Hotels: disable swipe gesture when gallery modal is open

RNAndroidPlayground/dependencies.gradle, RNAndroidPlayground/react-native/build.gradle, RNAndroidPlayground/react-native/settings.gradle, scripts/buildAndroidSnapshots.js
=> Android build snapshots improvements

.eslintrc.js, app/hotels/src/navigation/singleHotel/SingleHotelStack.js, packages/shared/src/view/DimensionsConsumer.js, packages/shared/src/view/__tests__/AdaptableLayout.test.js, packages/shared/src/view/__tests__/__snapshots__/AdaptableLayout.test.js.snap
=> Android: Fix when no passing dimensions

app/hotels/src/allHotels/searchForm/LocationButton.js, app/hotels/src/allHotels/searchForm/guests/Guests.js, app/hotels/src/filter/FilterButton.js, packages/navigation/index.js, packages/shared/src/forms/datePicker/DatePickerButton.js
Toolbar elevation 2dp
corner radius of inputs 2pd
closes #798
=> Hotels: Apply styling for new design guidelines

app/MMB/src/scenes/list/__generated__/FlightListContainerQuery.graphql.js, app/MMB/src/scenes/list/__generated__/FlightsQuery.graphql.js, app/MMB/src/scenes/list/cityImage/DateAndPassengerCount.js, app/MMB/src/scenes/list/cityImage/ImageBadges.js, app/MMB/src/scenes/list/cityImage/StatusBadge.js, app/MMB/src/scenes/list/cityImage/__generated__/ImageBadges.graphql.js, app/MMB/src/scenes/list/cityImage/__generated__/StatusBadge.graphql.js, packages/localization/src/vocabularies/ManageMyBooking.js
=> MMB: Booking list style updates

app/MMB/src/scenes/timeline/Timeline.js, app/MMB/src/scenes/timeline/__generated__/TimelineQuery.graphql.js, app/MMB/src/scenes/timeline/events/DownloadBoardingPassTimelineEvent.js, app/MMB/src/scenes/timeline/events/__generated__/DownloadBoardingPassTimelineEvent.graphql.js, packages/localization/src/vocabularies/ManageMyBooking.js, schema.graphql
Button functionality TODO (i.e. BoardingPass viewer component, etc.)
=> Adding DownloadBoardingPass Event

packages/localization/src/vocabularies/ManageMyBooking.js
fixes #813 
(wrong number in the branch name...)
=> Fixing label

app/MMB/src/scenes/timeline/TimelineEvent.js, app/MMB/src/scenes/timeline/TimelineEventDateLocation.js, app/MMB/src/scenes/timeline/__generated__/TimelineQuery.graphql.js, app/MMB/src/scenes/timeline/events/DepartureTimelineEvent/DepartureTimelineEventNote.js, app/MMB/src/scenes/timeline/events/DepartureTimelineEvent/__generated__/DepartureTimelineEvent.graphql.js, app/MMB/src/scenes/timeline/events/DepartureTimelineEvent/index.js, packages/localization/src/vocabularies/ManageMyBooking.js, schema.graphql
=> Adding flight info to Departure component

app/MMB/src/components/CityImage.js, app/MMB/src/scenes/list/MulticityFlight.js, app/MMB/src/scenes/list/OneWayFlight.js, app/MMB/src/scenes/list/ReturnFlight.js, app/MMB/src/scenes/list/__generated__/FlightListContainerQuery.graphql.js, app/MMB/src/scenes/list/__generated__/FlightsQuery.graphql.js, app/MMB/src/scenes/list/__generated__/MulticityFlight_booking.graphql.js, app/MMB/src/scenes/list/__generated__/OneWayFlight_booking.graphql.js, app/MMB/src/scenes/list/__generated__/ReturnFlight_booking.graphql.js, app/MMB/src/scenes/list/cityImage/CityImageContainer.js, app/MMB/src/scenes/list/cityImage/__generated__/CityImageContainer_arrival.graphql.js, app/MMB/src/scenes/list/cityImage/__generated__/CityImageContainer_departure.graphql.js, app/MMB/src/scenes/list/cityImage/__generated__/CityImageContainer_image.graphql.js, app/MMB/src/scenes/travelDocument/FillTravelDocument.js, app/MMB/src/scenes/travelDocument/__generated__/FillTravelDocument.graphql.js, app/MMB/src/scenes/travelDocument/__generated__/FillTravelDocumentContainerQuery.graphql.js, app/MMB/src/scenes/travelDocument/__generated__/FillTravelDocumentQuery.graphql.js
Also rename CityImage component to CityImageContainer and create re-usable city image component
=> MMB: Fill travel document add city image

app/MMB/src/components/ScrollIntoView.js, app/MMB/src/scenes/timeline/Timeline.js
=> Scrolling into view future event closest to today

app/MMB/src/components/header/Header.js, app/MMB/src/components/header/MobileTripOverviewHandle.js, packages/shared/src/icons/TextIcon.js
and removing visual feedback on Touchable
=> Adding missing animations on TripOverview in Booking Details

app/MMB/src/navigation/FillTravelDocumentScreen.js
=> MMB: Make fill travel document header fit on mobile

app/MMB/src/components/TitleTranslation.js, app/MMB/src/navigation/TravelDocumentModalScreen.js, app/MMB/src/scenes/travelDocument/__generated__/FillTravelDocumentContainerQuery.graphql.js, app/MMB/src/scenes/travelDocument/__generated__/FillTravelDocumentQuery.graphql.js, app/MMB/src/scenes/travelDocument/menuItem/PassengerMenuItem.js, app/MMB/src/scenes/travelDocument/menuItem/__generated__/PassengerMenuItem.graphql.js, packages/localization/index.js, packages/localization/src/vocabularies/ManageMyBooking.js, packages/shared/index.js, packages/shared/src/forms/Switch.js, packages/shared/src/forms/datePicker/DatePicker.android.js, packages/shared/src/forms/datePicker/DatePicker.ios.js, packages/shared/src/forms/datePicker/DatePickerButton.js, packages/shared/src/forms/datePicker/DatePickerProps.js
TODO: Submitting and validation
=> MMB: Add form for filling in travel document data

app/hotels/src/filter/FilterButton.js
=> Hotels: Fix filter button color code

app/hotels/src/singleHotel/HotelDetailScreen.js
=> Hotels: Add padding bottom to hotel detail screen

RNAndroidPlayground/app/src/main/res/layout/activity_main.xml, RNAndroidPlayground/app/src/main/res/values/styles.xml, android/app/src/main/res/values/styles.xml, packages/shared/src/view/Layout.js
Fixes #858.
Pending to test the same style in the production app.
=> Android: set StatusBar translucent using native code

app/hotels/src/map/BottomSheetHandle.js
=> Hotels: Fix drag indicator styling

app/hotels/src/singleHotel/roomList/RoomImage.js
=> Hotels: Remove border radius from room image overlay

app/hotels/src/singleHotel/hotelInformation/description/Description.js, app/hotels/src/singleHotel/hotelInformation/description/Facilities.js, app/hotels/src/singleHotel/roomList/RoomDescription.js, app/hotels/src/singleHotel/roomList/__tests__/__snapshots__/RoomDescription.test.js.snap, packages/localization/src/vocabularies/Hotels.js, packages/shared/src/ReadMore.js, packages/shared/src/__tests__/ReadMore.test.js
=> Shared: Change font weight and translate read more

app/hotels/src/singleHotel/brandLabel/BrandLabel.js, app/hotels/src/singleHotel/brandLabel/__tests__/__snapshots__/BrandLabel.test.js.snap
=> Hotels: Fix booking label size

app/hotels/src/filter/hotelFacilities/HotelFacilitiesPopup.js, app/hotels/src/filter/stars/StarsPopup.js, app/hotels/src/filter/stars/__tests__/__snapshots__/StarsPopup.test.js.snap
=> Hotels: Change separator size for filters

app/profile/components/SaveCustomToken.js, app/profile/index.js
Currently we only have login with email and password. I need to access bookings on an account with facebook login to test apple-wallet integration, so we need to be able to save a custom token.
=> Profile: Allow saving custom token

packages/navigation/index.js
=> fix: Transparent header with react-navigation 2

app/hotels/src/filter/FilterButton.js, packages/shared/src/buttons/Button.js
=> Shared: Apply correct button styles

app/hotels/src/allHotels/searchForm/guests/Guests.js, packages/shared/src/forms/datePicker/DatePickerButton.js
=> fix: Add elevation to guests picker and date picker

app/hotels/src/singleHotel/PaymentScreen.js, app/hotels/src/singleHotel/__tests__/PaymentScreen.test.js, app/hotels/src/singleHotel/__tests__/__snapshots__/PaymentScreen.test.js.snap, packages/shared/index.js, packages/shared/src/WebView.js, packages/shared/types/Events.js
=> Hotels: Add ancillaryPurchased logging event when hotel is paid for

app/hotels/src/navigation/allHotels/AllHotelsNavigationScreen.js, app/hotels/src/navigation/allHotels/__tests__/AllHotelsNavigationScreen.test.js, app/hotels/src/navigation/allHotels/__tests__/__snapshots__/AllHotelsNavigationScreen.test.js.snap, app/hotels/src/navigation/singleHotel/SingleHotelNavigationScreen.js, packages/localization/src/DefaultVocabulary.js, packages/shared/index.js, packages/shared/src/WithNativeNavigation.js, packages/shared/src/WithStandaloneScreen.js, packages/shared/src/__tests__/WithNativeNavigation.test.js
=> Fix single hotel module for present/push on native

.eslintrc.js, app/MMB/index.js, app/MMB/src/navigation/TravelDocumentModalScreen.js, app/MMB/src/navigation/__tests__/TravelDocumentModalScreen.test.js, app/MMB/src/navigation/mutation/UpdatePassenger.js, app/MMB/src/scenes/travelDocument/form/ExpiryDatePicker.js, app/MMB/src/scenes/travelDocument/form/IdInput.js, app/MMB/src/scenes/travelDocument/form/TravelDocumentForm.js, app/MMB/src/scenes/travelDocument/form/TravelDocumentFormContext.js, app/MMB/src/scenes/travelDocument/menuItem/TravelDocumentPassengerMenuItem.js, packages/relay/index.js, packages/relay/src/AuthContext.js, packages/shared/src/forms/Switch.js
Basically moving state to a context, and create smaller components
=> MMB: Refactor TravelDocumentModalScreen

app/MMB/index.js, app/MMB/src/navigation/ListScreen.js, app/MMB/src/scenes/list/Flight.js, app/MMB/src/scenes/list/FlightItemLayout.js, app/MMB/src/scenes/list/FlightList.js, app/MMB/src/scenes/list/FlightListContainer.js, app/MMB/src/scenes/list/FlightListLayout.js, app/MMB/src/scenes/list/__generated__/FlightQuery.graphql.js, app/core/src/screens/MMBPackageWrapper.js, app/profile/components/SaveSimpleToken.js, app/profile/index.js, packages/relay/src/AuthContext.js, schema.graphql
Nothing will happen yet when you click on a booking when using simple token. That is up in the next PR.
=> MMB: Prepare List screen for simple token usage

app/core/src/screens/HotelsPackageWrapper.js, app/core/src/screens/SingleHotelPackageWrapper.js, app/hotels/README.md, app/hotels/src/CoordinatesType.js, app/hotels/src/HotelsContext.js, app/hotels/src/appRegistry/HotelsStandalonePackage.js, app/hotels/src/appRegistry/RootComponent.js, app/hotels/src/appRegistry/SingleHotelStandalonePackage.js, app/hotels/src/singleHotel/PaymentScreen.js, app/hotels/src/singleHotel/__tests__/PaymentScreen.test.js, app/hotels/src/singleHotel/__tests__/__snapshots__/PaymentScreen.test.js.snap
@ferrannp please also have a look at this, it will involve some changes to the playgrounds I assume.
=> Hotels: Add label passed from native to payment screen

app/MMB/src/components/TitleTranslation.js, app/MMB/src/menuGroups/passengerMenuGroup/Passenger.js, app/MMB/src/scenes/passenger/Passenger.js, app/MMB/src/scenes/passenger/PassengerMenuItem.js, app/MMB/src/scenes/passenger/__tests__/__snapshots__/Passenger.test.js.snap, app/MMB/src/scenes/travelDocument/form/TravelDocumentForm.js, packages/localization/src/vocabularies/ManageMyBooking.js
=> Improving TitleTranslation

app/MMB/src/components/exploreCity/ExploreButton.js, app/MMB/src/components/exploreCity/ExploreText.js, packages/localization/src/vocabularies/ManageMyBooking.js
=> MMB: Add explore button

app/MMB/src/menuGroups/TripInfoMenuGroup.js, app/MMB/src/navigation/DetailScreen.js, app/MMB/src/scenes/explore/Explore.js, app/MMB/src/scenes/explore/ExploreAirportGroup.js, app/MMB/src/scenes/explore/ExploreBookingMulticity.js, app/MMB/src/scenes/explore/ExploreBookingOneWay.js, app/MMB/src/scenes/explore/ExploreBookingReturn.js, app/MMB/src/scenes/explore/ExploreDestinationsGroup.js, app/MMB/src/scenes/explore/GetValidExploreType.js, app/MMB/src/scenes/explore/__generated__/ExploreAirportGroup.graphql.js, app/MMB/src/scenes/explore/__generated__/ExploreBookingMulticity.graphql.js, app/MMB/src/scenes/explore/__generated__/ExploreBookingOneWay.graphql.js, app/MMB/src/scenes/explore/__generated__/ExploreBookingReturn.graphql.js, app/MMB/src/scenes/explore/__generated__/ExploreDestinationsGroup.graphql.js, app/MMB/src/scenes/explore/__generated__/ExploreQuery.graphql.js, packages/localization/src/vocabularies/ManageMyBooking.js, packages/navigation/src/MenuItemIcon.js
=> Feat:  Explore screen

app/MMB/src/scenes/help/Help.js, app/hotels/src/filter/hotelFacilities/HotelFacilitiesPopup.js, app/hotels/src/filter/price/PricePopup.js, app/hotels/src/filter/score/ScorePopup.js, app/hotels/src/filter/stars/StarsPopup.js, app/hotels/src/navigation/NewNavigationStack.js
=> Hotels: disable values from changing in visible popup

.build/package.json, RNAndroidPlayground/app/src/main/java/com/kiwi/rnandroidplayground/HotelActivity.kt, RNAndroidPlayground/app/src/main/java/com/kiwi/rnandroidplayground/HotelsModulesInjection.kt, RNAndroidPlayground/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/RNHotelsActivity.kt, RNAndroidPlayground/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/RNKiwiActivity.kt
=> rnkiwimobile extensible for multiple apps

RNAndroidPlayground/react-native-native-modules/src/main/java/com/skypicker/reactnative/nativemodules/translation/RNTranslationManager.kt, app/core/config/NativeModulesMocks/RNTranslationManager.js, ios/RNModules/RNTranslationManager/RNTranslationManager/RNTranslationManager.m, packages/localization/src/CancellableTranslation.js, packages/localization/src/__tests__/Translation.test.js, packages/rnmodules/index.js, packages/rnmodules/translation/README.md, packages/rnmodules/translation/TranslationManager.js
* remove `translate` method
*NOTE:* Current `translate` method is former `translateAsync`
=> Remove redundant translate method

.build/package.json, RNAndroidPlayground/dependencies.gradle, RNAndroidPlayground/react-native-native-modules/build.gradle, packages/rnmodules/package.json, scripts/buildAndroidSnapshots.js
=> Android: Deploy react-native-native-modules automatically (rnmodules)

app/MMB/src/scenes/tickets/boardingPassesPdf/BoardingPassPdf.js, app/MMB/src/scenes/tickets/boardingPassesPdf/__tests__/BoardingPassPdf.test.js
Basically doing this so it will be easier to determine if of we have downloaded and stored boarding passes for the booking.
=> MMB: Add bookingId to boardingPass file name

app/MMB/index.js, app/MMB/src/context/GoogleMapsContext.js, app/MMB/src/navigation/AddressPickerScreen.js, app/MMB/src/navigation/NavigationStack.js, app/MMB/src/scenes/tripServices/LocationPopupButton.js, app/MMB/src/scenes/tripServices/TripServiceRefreshContainer.js, app/MMB/src/scenes/tripServices/__generated__/TripServiceRefreshContainerQuery.graphql.js, app/MMB/src/scenes/tripServices/__generated__/TripServicesQuery.graphql.js, app/MMB/src/scenes/tripServices/transportation/AddressLocationLegend.js, app/MMB/src/scenes/tripServices/transportation/CurrentPositionButton.js, app/MMB/src/scenes/tripServices/transportation/MarkerA.js, app/MMB/src/scenes/tripServices/transportation/MarkerB.js, app/MMB/src/scenes/tripServices/transportation/MarkerLocationButton.js, app/MMB/src/scenes/tripServices/transportation/TransportationMap.js, app/MMB/src/scenes/tripServices/transportation/TransportationMapMarker.js, app/MMB/src/scenes/tripServices/transportation/__tests__/TransportationMap.test.js, app/MMB/src/scenes/tripServices/transportationMenuItem/TransportLocationItem.js, app/MMB/src/scenes/tripServices/transportationMenuItem/TransportationMenuItem.js, app/MMB/src/scenes/tripServices/transportationMenuItem/__generated__/TransportLocationItem.graphql.js, app/MMB/src/scenes/tripServices/transportationMenuItem/__generated__/TransportationMenuItem.graphql.js, app/core/config/application.js, app/core/src/screens/bookingsStack/MMBPackageWrapper.js, packages/localization/src/DateFormatter.js, packages/localization/src/vocabularies/ManageMyBooking.js, packages/navigation/types/Navigation.js, packages/shared/index.js, packages/shared/src/DropMarker.js, packages/shared/src/PositionMarker.js, schema.graphql
Add transportation menu item
Add current location item
Remove wrong icons
Add deeplinking
=> Adding transportation in trip services

RNAndroidPlayground/react-native-native-modules/src/main/java/com/skypicker/reactnative/nativemodules/card/Card.kt, RNAndroidPlayground/react-native-native-modules/src/main/java/com/skypicker/reactnative/nativemodules/card/CardCallback.kt, RNAndroidPlayground/react-native-native-modules/src/main/java/com/skypicker/reactnative/nativemodules/card/RNCardManager.kt, RNAndroidPlayground/react-native-native-modules/src/main/java/com/skypicker/reactnative/nativemodules/card/RNCardManagerPackage.kt, android/app/src/main/java/com/reactnativeapp/MainApplication.java, packages/rnmodules/card/CardManager.js, packages/rnmodules/card/README.md, packages/rnmodules/index.js
- Prepared to be implemented by native apps that consume it
- Provides a mock implementation using shared preferences
=> Android card module Native<->JS protocol

.eslintrc.js, app/MMB/src/scenes/tripServices/transportationMenuItem/TransportationMenuItem.js, app/hotels/src/allHotels/searchForm/locationPicker/LocationPicker.js, app/hotels/src/search/SearchQueryHelpers.js, app/hotels/src/singleHotel/roomList/RoomBadges.js, packages/localization/package.json, packages/localization/src/Alert.js, packages/localization/src/Translation.js, packages/localization/src/TranslationHelpers.js, packages/localization/src/__tests__/Translation.test.js, packages/rnmodules/translation/TranslationManager.js, packages/shared/src/PlatformStyleSheet.js, scripts/releaseFramework.js
=> Localization: Fix broken translation promise

docs/ios/native-dependencies.md, ios/Podfile
=> Adjust podfile for ios framework

packages/shared/src/popup/ButtonPopup.js, packages/shared/src/popup/Popup.js, packages/shared/src/popup/__tests__/__snapshots__/ButtonPopupPlayground.test.js.snap
=> Hotels: Position save and close button outside scroll view in popup

docs/ios/README.md, ios/reactNativeApp.xcodeproj/xcshareddata/xcschemes/RNNativePlayground.xcscheme
=> Update docs with commands to run playground in debug/release mode

android/playground/src/main/java/com/kiwi/rnandroidplayground/HotelsData.kt, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/hotels/RNHotelsModule.kt, docs/android/usage-in-real-app.md
First two points of https://github.com/kiwicom/mobile/issues/1129 + fixes on initial props of Hotels (some were left hardcoded).
=> Add usage-in-real-app.md for Android + initial hotel props fixes

android/app/build.gradle, android/dependencies.gradle, android/native/react-native-maps/build.gradle, android/native/react-native-maps/settings.gradle, android/native/react-native-native-modules/build.gradle, android/native/react-native-tooltips/build.gradle, android/native/react-native-tooltips/settings.gradle, android/native/react-native-vector-icons/build.gradle, android/native/react-native-vector-icons/settings.gradle, android/native/react-native-zip-archive/build.gradle, android/native/react-native-zip-archive/settings.gradle, android/native/react-native/build.gradle, android/native/react-native/settings.gradle, android/native/versions.gradle, android/playground/build.gradle, android/rnkiwimobile/build.gradle, android/rnkiwimobile/versions.gradle, docs/android/external-native-dependencies.md, scripts/buildAndroidSnapshots.js
=> Fix command now that there is native folder inside android

app/hotels/src/gallery/GalleryGrid.js, app/hotels/src/navigation/HotelsNavigationStack.js, app/hotels/src/navigation/singleHotel/SingleHotelNavigationScreen.js, app/hotels/src/navigation/singleHotel/SingleHotelStack.js, app/hotels/src/singleHotel/PaymentScreen.js, app/hotels/src/singleHotel/__tests__/__snapshots__/PaymentScreen.test.js.snap, packages/navigation/index.js
Gallery and payments as screens instead of new modal
=> Hotels: Fix status bar on gallery

app/hotels/src/singleHotel/roomList/RoomImage.js, app/hotels/src/singleHotel/roomList/RoomList.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/hotels/src/singleHotel/roomList/__tests__/__snapshots__/RoomImage.test.js.snap
Image with correct border radius
=> Fix: Single Hotel Room List - no separator after last room - image with correct border radius

app/hotels/src/allHotels/AllHotelsSearchList.js, app/hotels/src/allHotels/AllHotelsSearchRow.js, app/hotels/src/allHotels/NewAllHotelsSearch.js, app/hotels/src/allHotels/RenderSearchResults.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchList.graphql.js, app/hotels/src/allHotels/__generated__/NewAllHotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__generated__/RenderSearchResultsQuery.graphql.js, app/hotels/src/allHotels/__tests__/AllHotelsSearchList.test.js, app/hotels/src/allHotels/__tests__/__snapshots__/AllHotelsSearchList.test.js.snap, app/hotels/src/map/allHotels/HotelSwipeItem.js, app/hotels/src/map/allHotels/HotelSwipeList.js, app/hotels/src/map/allHotels/MapScreen.js, app/hotels/src/map/allHotels/__generated__/MapScreen.graphql.js, app/hotels/src/navigation/allHotels/MapHeaderButton.android.js, app/hotels/src/navigation/allHotels/MapHeaderButton.ios.js, app/hotels/src/navigation/allHotels/SearchResultsScreen.js, e2e/hotels.spec.js, packages/navigation/src/HeaderButton.js, packages/shared/src/TouchableWithoutFeedback.js
Small refactor to avoid 5-level prop-drilling
/!\ We need to agree on a Hotels Context /!\
=> Add: Hotels map available on tablet

app/hotels/src/gallery/GalleryGrid.js, app/hotels/src/singleHotel/header/Header.js, e2e/hotels.spec.js
=> Add: e2e test for hotel gallery screen

app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/PaymentScreen.js, app/hotels/src/singleHotel/__generated__/HotelDetailScreen_availableHotel.graphql.js, app/hotels/src/singleHotel/__generated__/PaymentScreenQuery.graphql.js, app/hotels/src/singleHotel/__generated__/SingleHotelContainerQuery.graphql.js, app/hotels/src/singleHotel/__tests__/__snapshots__/PaymentScreen.test.js.snap, app/hotels/src/singleHotel/bookNow/__tests__/countBookingPrice.test.js, app/hotels/src/singleHotel/bookNow/countBookingPrice.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/hotels/src/singleHotel/roomList/__generated__/RoomRow_availableRoom.graphql.js, schema.graphql
And revert the reverted commit 🤕
=>  Hotels: Get original room id from graphql query

app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/roomList/RoomList.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/hotels/src/singleHotel/roomList/__tests__/RoomRow.test.js, app/hotels/src/singleHotel/roomPicker/IncrementDecrement.js, app/hotels/src/singleHotel/roomPicker/RoomPicker.js, app/hotels/src/singleHotel/roomPicker/SelectButton.js, app/hotels/src/singleHotel/roomPicker/__tests__/RoomPicker.test.js, app/hotels/src/singleHotel/roomPicker/__tests__/__snapshots__/RoomPicker.test.js.snap, packages/playground/src/PlaygroundRenderer.js, packages/shared/src/__tests__/SliderLabels.test.js, packages/shared/src/buttons/IncrementDecrementButtons.js, packages/shared/src/forms/__tests__/Checkbox.test.js
I believe this prop-drilling should be improved.
=> Improvement: Prevent selecting more rooms than there are guests

.build/package.json, package.json, packages/shared/package.json, scripts/buildAndroidSnapshots.js, yarn.lock
=> Update react-native to 0.57.4 and react-native-maps to 0.22.0

app/hotels/src/HotelsContext.js, app/hotels/src/__tests__/HotelsContext.test.js, app/hotels/src/allHotels/AllHotelsSearchRow.js, app/hotels/src/allHotels/Stay22HotelsSearch.js, app/hotels/src/allHotels/__tests__/Stay22HotelsSearch.test.js, app/hotels/src/map/allHotels/HotelSwipeItem.js, app/hotels/src/navigation/allHotels/SearchResultsScreen.js, app/hotels/src/navigation/singleHotel/SingleHotelContext.js, app/hotels/src/navigation/singleHotel/SingleHotelNavigationScreen.js, app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/SingleHotelContainer.js, app/hotels/src/singleHotel/Stay22SingleHotel.js, app/hotels/src/singleHotel/__generated__/HotelDetailScreen_availableHotel.graphql.js, app/hotels/src/singleHotel/__generated__/Stay22SingleHotelQuery.graphql.js, app/hotels/src/singleHotel/hotelInformation/HotelInformation.js, app/hotels/src/singleHotel/hotelInformation/__generated__/HotelInformation_hotel.graphql.js, app/hotels/src/singleHotel/hotelInformation/location/Location.js, app/hotels/src/singleHotel/hotelInformation/location/__generated__/Location_hotel.graphql.js, app/hotels/src/singleHotel/roomList/RoomRow.js, schema.graphql
Waiting for gql PR to be merged first
=> Hotels: Add stay 22 detail query support

app/hotels/src/appRegistry/NewHotelsStandalonePackage.js, app/hotels/src/navigation/HotelsTabletStack.js
=> Hotels: Create tablet navigation stack

android/app/build.gradle, android/settings.gradle, ios/reactNativeApp.xcodeproj/project.pbxproj, scripts/configureApplication.js
Fixes https://github.com/kiwicom/mobile/issues/1274.
=> Patching react-native-code-push for linking assets

docs/android/README.md, docs/common/code-push.md
=> Add common and Android docs for CodePush

app/MMB/src/scenes/list/FlightList.js
Note: this would never happen in production(if we ever get there) since
we would not get to this screen unless we are logged in
=> MMB: Fix crash on my bookings screen when not logged in

app/hotels/src/HotelsContext.js, app/hotels/src/__tests__/HotelsContext.test.js, app/hotels/src/appRegistry/RootComponent.js, app/hotels/src/appRegistry/__tests__/RootComponent.test.js, app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/HotelDetailScreenContext.js, app/hotels/src/singleHotel/RoomSummary.js, app/hotels/src/singleHotel/__tests__/HotelDetailScreenContext.test.js, app/hotels/src/singleHotel/bookNow/BookNow.js, app/hotels/src/singleHotel/bookNow/__tests__/countBookingPrice.test.js, app/hotels/src/singleHotel/bookNow/countBookingPrice.js, app/hotels/src/singleHotel/roomList/RoomList.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/hotels/src/singleHotel/roomList/__tests__/RoomRow.test.js
We need this context when adding offline screen to hotel details
=> Hotels: Refactor state logic from HotelDetailScreen to context

.build/package.json, android/app/build.gradle, android/app/src/main/java/com/reactnativeapp/MainApplication.java, android/build.gradle, android/rnkiwimobile/build.gradle, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/hotels/RNHotelsModule.kt, android/rnkiwimobile/versions.gradle, android/settings.gradle, app/MMB/src/navigation/NavigationStack.js, app/core/src/navigation/index.js, app/core/src/navigation/stacks/HotelsStack.js, ios/Podfile, package.json, packages/navigation/index.js, packages/navigation/package.json, scripts/buildAndroidSnapshots.js, yarn.lock
=> Update to react-navigation 3.0.0

.build/package.json, package.json, packages/shared/package.json, yarn.lock
Fixes #1371.
The new version after so many months was dropping tones of Android fps and freezing the app.
=> Downgrade react-native-maps

scripts/configureApplication.js
Fixes https://github.com/kiwicom/mobile/issues/1376.
=> Patching react-native-maps for Android Studio to be able to sync

.build/package.json, android/playground/src/main/AndroidManifest.xml, android/playground/src/main/java/com/kiwi/mobile/rnandroidplayground/HotelsData.kt, android/playground/src/main/java/com/kiwi/mobile/rnandroidplayground/HotelsStay22Activity.kt, android/playground/src/main/java/com/kiwi/mobile/rnandroidplayground/MainActivity.kt, android/playground/src/main/res/layout/activity_main.xml, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/hotels/RNHotelsInitialProperties.kt, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/hotels/RNHotelsModule.kt
Closes #1362.
@tbergq let me know if this is what we expect.
=> Add Stay22 options to Android playground

package.json
Should I also change framework version @ferrannp ?
=> CodePush target-version 6.0.0

docs/android/react-native-native-modules.md
=> Update and rename react-native-native-modules.md

app/hotels/src/filter/price/PriceFilter.js, app/hotels/src/filter/price/PricePopup.js, packages/localization/src/TranslationHelpers.js, packages/localization/src/__tests__/TranslationHelpers.test.js, packages/localization/src/vocabularies/Hotels.js, packages/shared/src/SliderLabels.js
[jira](https://jira.kiwi.com/browse/MOBILE-2147)
=> Translation fix

app/hotels/src/allHotels/RenderSearchResults.js
=> Calculate map position based on screen height

app/core/src/screens/hotelsStack/Homepage.js, app/hotels/src/singleHotel/bookNow/BookNow.js, app/hotels/src/singleHotel/bookNow/__tests__/BookNow.test.js, packages/localization/src/vocabularies/Hotels.js
We want to let the user know when he is searching for hotels for 5 persons,
but selects beds for less than 5 persons
Also, we wait for next android release before we merge this feature. It can be deployed rapidly with code-push anyways 😄
=> Show warning when selected rooms don't have room for everyone

.build/package.json, app/MMB/src/scenes/tickets/boardingPasses/__tests__/FlightFromTo.test.js, app/hotels/src/allHotels/__tests__/__snapshots__/LoadMoreButton.test.js.snap, app/hotels/src/filter/stars/__tests__/__snapshots__/StarsPopup.test.js.snap, app/hotels/src/gallery/__tests__/__snapshots__/PhotosStripeHeader.test.js.snap, app/hotels/src/singleHotel/brandLabel/__tests__/__snapshots__/BrandLabel.test.js.snap, app/hotels/src/singleHotel/roomList/__tests__/__snapshots__/RoomImage.test.js.snap, package.json, packages/shared/src/__tests__/__snapshots__/AdaptableBadge.test.js.snap, packages/shared/src/__tests__/__snapshots__/Duration.test.js.snap, packages/shared/src/__tests__/__snapshots__/SliderLabels.test.js.snap, packages/shared/src/__tests__/__snapshots__/Touchable.ripple.test.js.snap, packages/shared/src/__tests__/__snapshots__/Touchable.test.js.snap, packages/shared/src/buttons/__tests__/__snapshots__/IncrementDecrementButtons.playground.test.js.snap, packages/shared/src/forms/__tests__/__snapshots__/Checkbox.test.js.snap, packages/shared/src/forms/__tests__/__snapshots__/Slider.test.js.snap, packages/shared/src/forms/__tests__/__snapshots__/TextInput.test.js.snap, packages/shared/src/forms/datePicker/__tests__/DatePicker.platform.test.js, packages/shared/src/offlineScreen/__tests__/__snapshots__/OfflineScreen.test.js.snap, packages/shared/src/popup/__tests__/__snapshots__/ButtonPopupPlayground.test.js.snap, yarn.lock
Fixes #1407.
Looks like they fixed the Snapshot issue they introduced in some version (as you can see in the updated ones).
Please test that every screen I might not be aware of works as expected.
=> Update react-native-code-push to 5.5.1, react-native to 0.57.8 and react to 16.6.3

ios/RNModules/RNLogging/RNLogging/RNLoggingModule.m
This PR adds missing nullability annotations to RNLoggingModule. Please, note that nullability annotations has to be defined also as part of `RCT_EXPORT_METHOD`.
=> Added missing nullability annotations 

.build/package.json, app/MMB/src/scenes/tickets/boardingPasses/__tests__/FlightFromTo.test.js, app/hotels/src/allHotels/__tests__/__snapshots__/LoadMoreButton.test.js.snap, app/hotels/src/filter/stars/__tests__/__snapshots__/StarsPopup.test.js.snap, app/hotels/src/gallery/__tests__/__snapshots__/PhotosStripeHeader.test.js.snap, app/hotels/src/singleHotel/brandLabel/__tests__/__snapshots__/BrandLabel.test.js.snap, app/hotels/src/singleHotel/roomList/__tests__/__snapshots__/RoomImage.test.js.snap, ios/RNModules/RNLogging/RNLogging/RNLoggingModule.m, package.json, packages/shared/src/__tests__/__snapshots__/AdaptableBadge.test.js.snap, packages/shared/src/__tests__/__snapshots__/Duration.test.js.snap, packages/shared/src/__tests__/__snapshots__/SliderLabels.test.js.snap, packages/shared/src/__tests__/__snapshots__/Touchable.ripple.test.js.snap, packages/shared/src/__tests__/__snapshots__/Touchable.test.js.snap, packages/shared/src/buttons/__tests__/__snapshots__/IncrementDecrementButtons.playground.test.js.snap, packages/shared/src/forms/__tests__/__snapshots__/Checkbox.test.js.snap, packages/shared/src/forms/__tests__/__snapshots__/Slider.test.js.snap, packages/shared/src/forms/__tests__/__snapshots__/TextInput.test.js.snap, packages/shared/src/forms/datePicker/__tests__/DatePicker.platform.test.js, packages/shared/src/offlineScreen/__tests__/__snapshots__/OfflineScreen.test.js.snap, packages/shared/src/popup/__tests__/__snapshots__/ButtonPopupPlayground.test.js.snap, yarn.lock
Logging fix and code-push/rn-update merged together. Should already be reviewed and tested.
=> Feature/target version 7.0

app/hotels/src/singleHotel/HotelDetailScreen.js
closes #1421
Powered by booking.com logo was not shown on iPhoneX
=> Add extra padding for iPhoneX in HotelDetailScreen

.eslintrc.js, app/hotels/src/navigation/singleHotel/SingleHotelNavigationScreen.js, app/hotels/src/singleHotel/bookNow/BookNow.js, app/hotels/src/singleHotel/bookNow/__tests__/BookNow.test.js, packages/shared/src/Logger.js
=> Hotels: Use rest of new log functions

app/App.js, app/native.js, app/polyfills/setPrototypeOf.js
=> Add polyfill for Object.setPrototypeOf

.eslintrc.js, app/hotels/src/singleHotel/HotelDetailScreen.js, packages/relay/src/Environment.js
closes #1411 
This should be the last part of cleanup after adding kiwicom eslint config
(I have ignored MMB for now, since it is not under active development)
=> Remove eslint disables

app/hotels/src/allHotels/RenderSearchResults.js
When there were few results after filtering, scrolling the list would
make item disappear in wrong place
JIRA-2288
=> Make search list wrapper flex 1

app/hotels/src/HotelsFilterContext.js, app/hotels/src/allHotels/NewAllHotelsSearch.js, app/hotels/src/filter/FilterParametersType.js, app/hotels/src/filter/FilterStripe.js, app/hotels/src/filter/hotelAmenities/HotelAmenitiesFilter.js, app/hotels/src/filter/hotelAmenities/HotelAmenitiesPopup.js
The button is called Amenities, this is to make naming more consistent
=> Hotels: Rename hotelFacilities to hotelAmenities

app/hotels/src/filter/hotelAmenities/HotelAmenities.js, app/hotels/src/filter/hotelAmenities/HotelAmenitiesPopup.js, app/hotels/src/filter/hotelAmenities/HotelAmenityCheckbox.js
Refactor component structure for hotel amenities
=> Hotels: Use icon component in HotelAmenities

app/App.js, app/core/package.json, app/core/src/screens/hotelsStack/Homepage.js, app/core/src/screens/hotelsStack/HotelsForm.js, app/core/src/screens/hotelsStack/HotelsFormContext.js, app/core/src/screens/hotelsStack/placepicker/HotelCityItem.js, app/core/src/screens/hotelsStack/placepicker/HotelCityList.js, app/core/src/screens/hotelsStack/placepicker/HotelCityQuery.js, app/core/src/screens/hotelsStack/placepicker/PlacepickerModal.js, app/core/src/screens/hotelsStack/placepicker/__generated__/HotelCityItem.graphql.js, app/core/src/screens/hotelsStack/placepicker/__generated__/HotelCityList.graphql.js, app/core/src/screens/hotelsStack/placepicker/__generated__/HotelCityQuery.graphql.js, packages/shared/src/forms/TextInput.js
It is not that pretty, but it is nice to be able to search in
different cities, different dates and room config
=> Add search form to homepage

app/MMB/src/components/header/__generated__/StatusBarIcon.graphql.js, app/MMB/src/scenes/list/cityImage/__generated__/StatusBadge.graphql.js, app/MMB/src/scenes/tripServices/__generated__/GeneralServicesMenuGroup.graphql.js, app/MMB/src/scenes/tripServices/insuranceMenuItem/__generated__/InsuranceMenuItemContainer.graphql.js, app/hotels/src/GraphQLSanitizers.js, app/hotels/src/__tests__/GraphQLSanitizers.test.js, app/hotels/src/allHotels/NewAllHotelsSearch.js, app/hotels/src/allHotels/__generated__/HotelsPaginationContainerQuery.graphql.js, app/hotels/src/allHotels/__generated__/NewAllHotelsSearchQuery.graphql.js, schema.graphql
closes #1440 
hotelFacilities has been deprecated on graphql server
=> Hotels: use hotelsAmenities field for filtering

README.md, android/app/build.gradle, android/app/src/androidTest/java/com/reactnativeapp/DetoxTest.java, android/build.gradle, android/dependencies.gradle, android/settings.gradle, e2e/config.json, e2e/hotels/hotelDetails/imageGallery.spec.js, package.json
=> E2e: Add setup for android phone

app/hotels/src/navigation/HotelsNavigationOptions.js, app/hotels/src/navigation/allHotels/SearchResultsScreen.js
Since header consists of headerLeft,
headerTitle and headerRight, it is impossible to
align the map button and header divider for
all possible sizes. This is the only approach
that will look decent
See [MOBILE-2427](https://jira.kiwi.com/secure/RapidBoard.jspa?rapidView=223&view=detail&selectedIssue=MOBILE-2427)
=> Hotels: Move header button to right on iPad

.build/package.json, README.md, android/app/build.gradle, android/dependencies.gradle, docs/common/changelog.md, ios/Podfile, ios/reactNativeApp.xcodeproj/project.pbxproj, package.json, packages/navigation/package.json, packages/shared/index.js, packages/shared/src/view/VerticalSwipeResponder.js, packages/shared/types/Events.js, yarn.lock
Upgrade other native dependencies as well
Write to readme how to test on android when you do react-native upgrade
closes #1414
=> Upgrade react-native to v0.58.3

app/fastTrack/src/appRegistry/FastTrackBanner.js, app/fastTrack/src/components/FastTrackModal.js
This is just a simple view that will serve for banner mock with integrated modal inside just for testing.
I will use this a fragment inside native app.
When I succeed integrating this banner and when we get new designs, I will refactor this and to it how it should be done.
=> Basic fast track banner mock

app/hotels/src/allHotels/__tests__/HotelsPaginationContainer.test.js, app/hotels/src/singleHotel/bookNow/__tests__/BookNow.test.js, packages/config/package.json, packages/playground/package.json, packages/relay/__tests__/index.test.js, packages/relay/package.json, packages/relay/src/__tests__/QueryRenderer.test.js, packages/rnmodules/package.json, packages/shared/src/__tests__/Price.test.js, packages/shared/src/buttons/__tests__/IncrementDecrementButtons.test.js, packages/shared/src/popup/__tests__/ButtonPopup.test.js, packages/shared/src/readMore/__tests__/ReadMoreLink.test.js, yarn.lock
No BC expected, e2e-tests pass
=> Upgrade dependencies

app/hotels/src/singleHotel/header/Header.js, app/hotels/src/singleHotel/hotelInformation/location/Location.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/hotels/src/singleHotel/roomList/RoomRowTitle.js
We have better flow types from @kiwicom/relay now
=> Delete unusable flow types from fragment container definition

.build/package.json, docs/common/changelog.md, package.json, yarn.lock
=> Upgrade react-native to 0.58.5

app/hotels/src/singleHotel/hotelInformation/description/Amenities.js, app/hotels/src/singleHotel/hotelInformation/description/Description.js
=> Hotels: Hide equipments label when there are no amenities

app/hotels/src/HotelsContext.js, app/hotels/src/__tests__/HotelsContext.test.js, app/hotels/src/navigation/HotelsNavigationOptions.js, app/hotels/src/navigation/allHotels/SearchDatepickers.js, app/hotels/src/navigation/allHotels/SearchResultsScreen.js, app/hotels/src/singleHotel/bookNow/__tests__/BookNow.test.js, app/hotels/src/singleHotel/header/__tests__/Header.test.js, app/hotels/src/singleHotel/hotelInformation/location/__tests__/Location.test.js, app/hotels/src/singleHotel/roomList/__tests__/RoomRow.test.js, packages/localization/package.json, packages/localization/src/DateUtils.js, packages/navigation/types/Navigation.js, yarn.lock
=> Hotels: Show datepicker when clicking on date in header

app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/header/Header.js, docs/common/changelog.md, packages/shared/index.js, packages/shared/src/statusbarBackground/StatusbarBackground.js, packages/shared/src/statusbarBackground/__tests__/StatusbarBackground.test.js
=> Hotels: Set background color on statusbar on ios

app/hotels/src/navigation/allHotels/SearchDatepickers.js, docs/common/changelog.md
=> Hotels: Fix cancel button in checkout datepicker

.build/package.json, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/RNKiwiHost.kt, docs/common/changelog.md
Upgrade rnkiwimobile to 0.0.44
closes #1492
=> Hotels: patch code-push-init android

packages/localization/package.json, packages/localization/src/DefaultVocabulary.js, packages/localization/src/Deployer.js, packages/localization/src/vocabularies/Hotels.js
Use @kiwicom/fetch in Deployer script
=> Localization: Delete unused keys

app/hotels/package.json, app/hotels/src/singleHotel/__generated__/BookingComSingleHotelQuery.graphql.js, app/hotels/src/singleHotel/__generated__/Stay22SingleHotelQuery.graphql.js, app/hotels/src/singleHotel/summary/ExtraCharges.js, app/hotels/src/singleHotel/summary/RoomSummary.js, app/hotels/src/singleHotel/summary/SummaryRow.js, app/hotels/src/singleHotel/summary/__generated__/RoomSummary_room.graphql.js, app/hotels/src/singleHotel/summary/__tests__/RoomSummary.test.js
Add slide up effect to show extra charges.
Note -> It is hard to trigger on emulator, better to test on device
closes #1490
=> Hotels: Add room cost and VAT

packages/relay/src/Environment.js
=> Catch sentry error and use it only in production

app/hotels/src/singleHotel/HotelDetailScreen.js, package.json, yarn.lock
=> Hotels: Add close modal to hotel not found error message

.build/package.json, android/app/build.gradle, android/app/src/debug/AndroidManifest.xml, android/app/src/debug/res/xml/react_native_config.xml, package.json, packages/navigation/package.json, yarn.lock
Upgrade react-navigation
Upgrade react-native-gesture-handler
Upgrade react-native-code-push
=> Upgrade react-native to 0.59.2

app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/__generated__/BookingComSingleHotelQuery.graphql.js, app/hotels/src/singleHotel/__generated__/HotelDetailScreen_availableHotel.graphql.js, app/hotels/src/singleHotel/__generated__/Stay22SingleHotelQuery.graphql.js, app/hotels/src/singleHotel/roomList/RoomList.js, app/hotels/src/singleHotel/roomList/__generated__/RoomList_data.graphql.js
This was causing a flow error which we surpressed in HotelDetailScreen
=> Hotels: Refactor RoomList to not use @relay(plural: true)

scripts/configureApplication.js
The fix has been merged into react-native itself
=> Remove patching of RCTUtils from configureApplication

android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/hotels/RNHotelsModule.kt, docs/android/external-native-dependencies.md
Update docs with missing step to add new native module
=> Add new native packages to RNHotelsModule

docs/common/changelog.md
=> Add release notes for target-version 10.0.0, bundle version 31

app/core/config/flow-typed/npm/decimal.js, app/hotels/package.json, app/hotels/src/singleHotel/summary/ExtraCharges.js, app/hotels/src/singleHotel/summary/RoomSummary.js, app/hotels/src/singleHotel/summary/__tests__/RoomSummary.test.js, packages/shared/package.json, packages/shared/src/Price.js, yarn.lock
=> Hotels: Add decimal.js to handle prices

packages/localization/src/scripts/Deployer.js, packages/localization/src/scripts/PhraseAppHelpers.js
=> Fix update-translation key

metro.config.js
We get 'System limit for number of file watchers reached' on CI
=> Deactivate watchman on CI

app/core/config/flow-typed/npm/decimal.js-light.js, app/hotels/package.json, app/hotels/src/singleHotel/summary/ExtraCharges.js, app/hotels/src/singleHotel/summary/RoomSummary.js, packages/shared/package.json, packages/shared/src/Price.js, yarn.lock
closes #1546
Basically same package, but lighter, we don't need all
functionality provided by main package
=> Hotels: Replace decimal package with decimal-light package

app/core/src/screens/hotelsStack/NewHotelsPackageWrapper.js
It was currently not that intuitive how to change currency in dev mode
=> Use currency set in homepage in NewHotelsPackageWrapper

scripts/configureApplication.js
Seems it is no longer necessary after upgrading
=> Remove react-native-maps patching

app/hotels/src/HotelsContext.js, app/hotels/src/allHotels/AllHotelsSearchList.js, app/hotels/src/allHotels/AllHotelsSearchRow.js, app/hotels/src/allHotels/HotelDistance.js, app/hotels/src/allHotels/HotelTitle.js, app/hotels/src/allHotels/HotelsPaginationContainer.js, app/hotels/src/allHotels/SearchRowContent.js, app/hotels/src/allHotels/__generated__/AllHotelsSearchRow_data.graphql.js, app/hotels/src/allHotels/__generated__/HotelsPaginationContainerQuery.graphql.js, app/hotels/src/allHotels/__generated__/NewAllHotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__generated__/SearchRowContent_hotel.graphql.js, app/hotels/src/allHotels/__generated__/Stay22HotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__generated__/Stay22PaginationContainerQuery.graphql.js, app/hotels/src/allHotels/__tests__/AllHotelsSearchList.test.js, app/hotels/src/allHotels/__tests__/HotelsPaginationContainer.test.js
AllHotelsSearchList
AllHotelsSearchRow
HotelsPaginationContainer
=> Use Hotels context as hook in

.eslintrc.js
=> Add WebView to restricted imports

.flowconfig, app/hotels/package.json, app/hotels/src/map/allHotels/HotelSwipeItem.js, app/hotels/src/map/allHotels/MapScreen.js, app/hotels/src/map/allHotels/MapView.js, app/hotels/src/map/singleHotel/SingleHotelMapScreen.js, app/hotels/src/map/singleHotel/Stay22SingleHotelMapScreen.js, app/hotels/src/navigation/allHotels/SearchResultsScreen.js, app/hotels/src/navigation/singleHotel/SingleHotelMapNavigationScreen.js, app/hotels/src/singleHotel/bookNow/BookNow.js, app/hotels/src/singleHotel/bookNow/__tests__/BookNow.test.js, package.json, yarn.lock
add react-native-testing-library
=> Hotels: Use hotels context as hook

.flowconfig, app/hotels/package.json, app/hotels/src/singleHotel/bookNow/__tests__/BookNow.test.js, package.json, yarn.lock
Remove react-native-testing-library since it caused more problems
than it solved
=> Fix book now test

app/hotels/src/navigation/DateButton.js, app/hotels/src/navigation/HotelsNavigationOptions.js, app/hotels/src/navigation/__tests__/DateButton.test.js
=> Hotels: Apply new styles to date header button

app/hotels/src/filter/FilterButton.js, app/hotels/src/filter/__tests__/FilterButton.test.js, app/hotels/src/filter/__tests__/__snapshots__/FilterButton.test.js.snap, packages/shared/src/icons/Icon.js
=> Hotels: Add new styles to filter button

app/hotels/src/filter/price/PricePopup.js, packages/shared/src/AdaptableBadge.js, packages/shared/src/__tests__/AdaptableBadge.test.js, packages/shared/src/__tests__/__snapshots__/AdaptableBadge.test.js.snap, packages/shared/src/forms/Slider.js, packages/shared/src/forms/SliderMarker.js, packages/shared/src/forms/__tests__/Slider.test.js, packages/shared/src/forms/__tests__/__snapshots__/Slider.test.js.snap
Shared: Add type info and circled prop to AdaptableBadge
Shared: Update slider to match with new design
=> Hotels: Update PricePopup with new design

app/hotels/src/map/hotelDetailPreview/HotelDetailPreview.js, app/hotels/src/map/hotelDetailPreview/HotelDetailPreviewContext.js, app/hotels/src/map/singleHotel/AdditionalInfo.js
Move onLayout to view under BottomSheet in AddtionalInfo
BottomSheet aligns content differently on phone and tablet.
Fixes MOBILE-4149
=> Hotels: Fix missing ratings on tablet

app/core/config/flow-typed/npm/decimal.js-light.js, app/hotels/src/allHotels/Stay22PaginationContainer.js, app/hotels/src/allHotels/__generated__/HotelsPaginationContainerQuery.graphql.js, app/hotels/src/allHotels/__generated__/NewAllHotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__generated__/Stay22HotelsSearchQuery.graphql.js, app/hotels/src/allHotels/__generated__/Stay22PaginationContainerQuery.graphql.js, app/hotels/src/allHotels/__generated__/Stay22PaginationContainer_data.graphql.js, packages/shared/src/Price.js, schema.graphql
Add complete flow types for decimal-light.
After this PR ->  #1611
=> Hotels: Set price stats to HotelsContext for stay22

app/hotels/src/HotelsContext.js, app/hotels/src/filter/CurrentSearchStatsType.js, app/hotels/src/filter/price/PriceFilter.js, app/hotels/src/filter/price/PricePopup.js, app/hotels/src/filter/price/PriceTitle.js
=> Hotels: Use decimal for priceStats

app/hotels/src/allHotels/NewAllHotelsSearch.js, app/hotels/src/filter/FilterParametersType.js, app/hotels/src/filter/price/PriceFilter.js
=> Hotels: Use decimal in HotelsFilterContext

app/hotels/src/filter/stars/StarsFilter.js
=> Hotels: Add stars behind the number of stars

packages/shared/src/toast/Toast.js, packages/shared/src/toast/__tests__/__snapshots__/Toast.test.js.snap
On android it ended up behind the filter stripe
=> Shared: Set zIndex for toast container view

packages/shared/src/toast/Toast.js, packages/shared/src/toast/__tests__/Toast.test.js, packages/shared/src/toast/__tests__/__snapshots__/Toast.test.js.snap
display: 'none' removes if from the view on ios
but for android the filter stripe became unclickable
=> Shared: Return null in toast when isVisible = false

.eslintrc.js, packages/localization/src/scripts/Deployer.js, packages/localization/src/scripts/PhraseAppHelpers.js, packages/navigation/index.js, packages/navigation/src/SplitNavigation.js, packages/navigation/src/withSplitNavigation.js, packages/relay/src/CacheManager.js
fix eslint-warning in split-navigation component
=> Clean up eslint-rules

app/hotels/src/allHotels/RenderSearchResults.js, app/hotels/src/allHotels/__tests__/RenderSearchResults.test.js
Rendering is slow because list view renders, and map view renders
even if only list view is visible. Changing behaviour to hide
map view, then show spinner until it is loaded entirely
=> Hotels: Fix performance issue on list page

app/hotels/src/singleHotel/__generated__/BookingComSingleHotelQuery.graphql.js, app/hotels/src/singleHotel/__generated__/Stay22SingleHotelQuery.graphql.js, app/hotels/src/singleHotel/roomList/BeddingInfo.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/hotels/src/singleHotel/roomList/RoomRowTitle.js, app/hotels/src/singleHotel/roomList/__generated__/BeddingInfo_room.graphql.js, app/hotels/src/singleHotel/roomList/__generated__/RoomRowTitle_room.graphql.js, app/hotels/src/singleHotel/roomList/__generated__/RoomRow_availableRoom.graphql.js, app/hotels/src/singleHotel/roomList/__tests__/formatBeddingInfo.test.js, schema.graphql
We showed maxPerson avaiable for room-type. Room type could be double room.
But there would be different block for 1 person living in it vs 2 persons.
This is the reason we had rooms that looked the exact same
with different prices.
=> Hotels: Show correct max number of guests

.build/package.json, app/core/config/NativeModulesMocks/ReactNativeGestureHandler.js, ios/Podfile, packages/navigation/package.json, packages/relay/package.json, packages/shared/package.json, yarn.lock
react-native-maps
react-native-gesture-handler
netinfo
react-native-webview
async-storage
=> Upgrade native-dependencies

android/react-native-native-modules/build.gradle, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/RNKiwiActivity.kt
Change root view to RNGestureHandlerEnabledRootView
=> Correctly link react-native-gesture-handler on anrdoid rnkiwimobile

.flowconfig, package.json, scripts/buildAndroidSnapshots.js
This is a quick fix to solve app crashing due to missing bundle.
The bundle is now probably add to the framework twice.
Someone with gradle/android knowledge should fix it in the gradle script
=> Bundle index.android.bundle into /src/main/assets of rnkiwimobile

app/hotels/src/allHotels/RenderSearchResults.js
Hide map and show map after animation is done
=> Fix map animation

app/account/package.json, app/account/src/appRegistry/AccountSettings.js, ios/RNKiwiMobile/RNKiwiConstants.m, ios/RNNativePlayground/Base.lproj/Main.storyboard, ios/RNNativePlayground/Info.plist, ios/RNNativePlayground/ViewController.m, ios/reactNativeApp.xcodeproj/project.pbxproj, yarn.lock
Inject local IP address into RNKiwiConstants
=> Upgrade accounts

app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/summary/SummaryButtons.js
Add white background to root component
Move margin from close button to book now button
Increase book now flex to 2 to match design
=> Design details on hotel detail screen

.build/package.json, ios/RNKiwiMobile/RNKiwiGestureController.m, package.json
Fixes [crashes](https://jira.kiwi.com/browse/MOBILE-7970) when building app with Xcode 11.
=> Dispatch gesture events on main queue

.build/package.json, android/dependencies.gradle, android/react-native-native-modules/build.gradle, package.json, packages/rnmodules/package.json
Fixes problem missing trinerdis-utils.
closes #1697
=> Update Android dependencies

ios/RNNativePlayground/Base.lproj/Main.storyboard, ios/RNNativePlayground/ViewController.h, ios/RNNativePlayground/ViewController.m
You can paste your account token in here, and it
will be passed down to RN code
=> Add token input field

.build/package.json, android/app/src/main/java/com/reactnativeapp/MainApplication.java, android/gradle.properties, android/playground/build.gradle, android/react-native-native-modules/src/main/java/com/skypicker/reactnative/nativemodules/account/AccountCallback.kt, android/react-native-native-modules/src/main/java/com/skypicker/reactnative/nativemodules/account/RNAccountManager.kt, android/react-native-native-modules/src/main/java/com/skypicker/reactnative/nativemodules/account/RNAccountManagerPackage.kt, android/rnkiwimobile/build.gradle, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/account/RNAccountModule.kt, app/hotels/src/filter/stars/StarsCheckbox.js, ios/Podfile.lock, packages/relay/src/AuthContext.js, packages/rnmodules/package.json, packages/shared/src/__tests__/PlatformStyleSheet.test.js, packages/shared/src/buttons/AppleWalletButton.ios.js, packages/shared/src/buttons/__tests__/ButtonTitle.test.js, packages/shared/src/forms/Checkbox.js, packages/shared/src/forms/TextInput.js
=> Add deleteAccount() callback.

package.json, yarn.lock
note: You may have to reinstall applesimutils
if applesimutils --list returns empty array, then you have to
=> Upgrade detox

app/account/package.json, app/account/src/WithAccountStack.js, ios/Podfile, ios/Podfile.lock, ios/RNKiwiMobile/RNKiwiViewController.m, ios/RNModules/RNAccountManager/Podfile, ios/RNModules/RNAccountManager/RNAccountManager.xcodeproj/project.pbxproj, ios/RNModules/RNAccountManager/RNAccountManager/RNAccountManager.h, ios/RNModules/RNAccountManager/RNAccountManager/RNAccountManager.m, ios/RNModules/RNModules.podspec, ios/reactNativeApp.xcodeproj/project.pbxproj, package.json, yarn.lock
Cleanup code on ios since it was broken
And move it to RNModules
=> Upgrade @kiwicom/account and pass bridge function

app/hotels/src/navigation/allHotels/MapHeaderButton.android.js, packages/shared/index.js, packages/shared/src/tooltip/Tooltip.js, packages/shared/src/tooltip/TooltipBubble.js
Use tooltip component in MapHeaderButton.android.js
=> Add tooltip component from universal-components to shared

e2e/hotels/hotelDetails/imageGallery.spec.js, package.json
Use iphone 11 for iphone tests
Do rotate test for tablet only
=> Run detox against production build for ios
