kiwicom/mobile

scripts/expo/commands/publishCodeReview.js
Reason: While PR is building, reviewer might be confused by old version of app.
It takes some time before build is finished, so I would like to avoid confusion by improving the comment (It already happened to me and you may forget this fact again)
=> Update comment that is automatically put into PR conversation

README.md
Note: GraphQL Playground doesn't work now (and we cannot upgrade). I am trying to solve it (https://github.com/graphql-cli/graphql-cli/issues/76) but I already wrote the docs so... :)
We'll see what will be the result. We can easily remove this dependency in case of additional problems. It's really easy to download introspection on our own and we can use https://kiwi-graphiql.now.sh/ instead of the Playground.
=> README: improve documentation around GraphQL

.eslintrc.js, .flowconfig, app/common/src/Color.js, app/common/src/map/PriceMarker.js, app/core/src/components/authentication/EmailLoginForm.js, app/core/src/screens/homepage/search/SearchHeaderForm.js, app/core/src/screens/searchResults/SearchResults.js, app/core/src/screens/singleBooking/SingleBooking.js, app/core/src/services/assets/AssetsDownloader.js, app/hotels/src/allHotels/AllHotels.js, app/hotels/src/allHotels/SearchForm.js, app/hotels/src/filter/FilterButton.js, app/hotels/src/filter/FilterStripe.js, app/relay/src/RelayQueryResponseCache.js
**Proposal**: I can see that underscore may be good visual clue providing information
about method being sort of private. But I have two arguments against:
1) Underscore method is not really private.
2) All React lifecycle methods are meant to be private but they are
not prefixed by the underscore which creates inconsistency and
additional confusion.
See: https://reactjs.org/docs/react-component.html#the-component-lifecycle
See: https://eslint.org/docs/rules/no-underscore-dangle
66646d5
=> Eslint: enable 'no-underscore-dangle' to unify naming

README.md, app/common/index.js, app/common/src/Color.js, app/common/src/errors/PartialFailure.js, app/common/src/map/__tests__/__snapshots__/DropMarker.test.js.snap, app/common/src/rating/Stars.js, app/hotels/src/allHotels/searchForm/__tests__/__snapshots__/SearchForm.test.js.snap, app/hotels/src/filter/__tests__/__snapshots__/FilterButton.test.js.snap, app/relay/index.js, app/relay/src/Environment.js, app/relay/src/QueryRenderer.js
Simple workaround for Relay bug (see: https://github.com/facebook/relay/issues/1913).
I have no idea how to write tests for this part of application.
I would prefer to merge this and think about it later since we will
need to refactor it a little bit because of other tests...
Related issue: #98
Checklist:
=> Handle partial GraphQL errors

.graphqlconfig.yaml, README.md, app/relay/scripts/RelayCompiler.js, package.json, schema.graphql, scripts/getSchema.js, yarn.lock
We need to keep one version of GraphQL but this dependency strictly
requires version '0.12.3'. As a result it downloads GraphQL snapshot
that is incompatible with Relay.
See: https://github.com/graphql-cli/graphql-cli/issues/76 (original
issue is resolved but it's still broken)
---
=> Remove 'graphql-cli' dependency

app/common/index.js, app/common/package.json, app/common/src/forms/Slider.js, app/common/src/popup/Popup.js, yarn.lock
**You can try a slider in #122**
Known issues
* ~~it should detect device orientation changed and recalculate slider length (use `react-native-orientation` or store screen dimensions in redux and check on `mapStateToProps`)~~
* snapped (jump by steps) is broken in lib, but it's not needed right now (see: https://github.com/ptomasroos/react-native-multi-slider/issues/49)
---
=> Common: add Slider component

app/common/index.js, app/common/src/Color.js, app/common/src/Icon.js, app/common/src/buttons/Button.js, app/common/src/forms/NumberControl.js, app/common/src/forms/TextInput.js, app/common/src/map/DropMarker.js, app/common/src/map/__tests__/__snapshots__/DropMarker.test.js.snap, app/core/src/screens/hotels/AllHotelsNavigationScreen.js, app/hotels/src/allHotels/searchForm/Guests.js, app/hotels/src/allHotels/searchForm/__tests__/__snapshots__/Guests.test.js.snap, app/hotels/src/filter/FilterButton.js, app/hotels/src/filter/price/PriceFilter.js, app/hotels/src/filter/stars/StarsCheckbox.js, app/hotels/src/filter/stars/StarsFilter.js, app/hotels/src/filter/stars/__tests__/__snapshots__/StarsCheckbox.test.js.snap, app/hotels/src/map/Address.js
This wraps `@expo/vector-icons` package and it will help us to do future
changes easily. We currently support only icons from material design
because these are the icons used in the design (only).
Closes: https://github.com/kiwicom/react-native-app/issues/94
---
=> Introduce new Icon component

app/hotels/src/allHotels/searchForm/guests/ChildrenAgesControl.js, app/hotels/src/allHotels/searchForm/guests/__tests__/ChildrenAgesControl.test.js
=> Fix guests age after first save

README.md, app/core/package.json, app/core/src/components/authentication/Logout.js, app/core/src/components/relay/PrivateApiRenderer.js, app/core/src/screens/hotels/AllHotelsMapNavigationScreen.js, app/core/src/screens/hotels/AllHotelsNavigationScreen.js, app/redux/index.js
This will allow connection to the Redux store from every component you
want. It's necessary to use 'react-native-app-redux' package to make
sure everything works. Redux itself should never be used directly
(except our wrapper package of course).
---
=> Redux: expose 'connect' function

README.md, ios/reactNativeApp.xcodeproj/project.pbxproj
Note: we currently do not support automated builds and build
distribution. This change just makes it possible to build and share iOS
builds in a fast way before we solve this automated path.
Closes #178
---
=> Docs: add info about application builds

app/hotels/src/map/MapView.js
=> Set the maximum limit of markers displayed in initial region

app/redux/src/ReduxContext.js
Methods 'componentWill*' are deprecated in next React version.
See: https://github.com/bvaughn/rfcs/blob/static-lifecycle-methods/text/0000-static-lifecycle-methods.md
---
=> ReduxContext: remove 'componentWillMount' method

app/common/package.json, yarn.lock
This change upgrades the dependency to the latest commit in the master
branch because they did not release the fixed version yet. We should
replace it later with something like '^0.0.12' (after the release).
See: https://github.com/ptomasroos/react-native-multi-slider/tree/2f83b6b8b700c0e6ace77c74b8af8a7d2ad83ba0
See: https://github.com/ptomasroos/react-native-multi-slider/pull/50
---
=> Shared: upgrade 'react-native-multi-slider' dependency

app/shared/src/Device.js, app/shared/src/__tests__/Device.test.js, app/shared/src/view/AdaptableLayout.js
Function `Device.subscribeToDimensionChanges` now returns unsubscribe
function (Redux pattern) so it's easy to unsubscribe during component
unmount. This way the `setState` won't be called on unmounted component.
=> AdaptableLayout: fix memory leak

app/hotels/src/allHotels/AllHotels.js
Unfortunately, these errors are not discovered by Flow because we use
untyped `connect` function for Redux and it effectively breaks Props
types.
=> Fix all hotels search coordinates

app/accessibility/index.js, app/accessibility/package.json, app/hotels/src/allHotels/searchForm/guests/Guests.js, app/hotels/src/allHotels/searchForm/guests/__tests__/__snapshots__/Guests.test.js.snap, app/hotels/src/singleHotel/bookNow/BookNow.js, app/hotels/src/singleHotel/bookNow/__tests__/__snapshots__/BookNow.test.js.snap, app/shared/package.json, app/shared/src/TouchableItem.js, app/shared/src/__tests__/TouchableItem.ripple.test.js, app/shared/src/__tests__/TouchableItem.test.js, app/shared/src/__tests__/__snapshots__/TouchableItem.ripple.test.js.snap, app/shared/src/__tests__/__snapshots__/TouchableItem.test.js.snap, app/shared/src/buttons/Button.js, app/shared/src/buttons/IncrementDecrementButtons.js, app/shared/src/buttons/__tests__/__snapshots__/Button.test.js.snap, app/shared/src/navigation/HeaderRightButton.js
I believe that being more restrictive and use exact props is much
better. This also adds default `activeOpacity={0.5}` to every element by
default so it's not necessary to set it manually (this is why I
actually started this change).
=> TouchableItem: use exact props

app/hotels/src/allHotels/HotelTitle.js, app/shared/src/Color.js
Line height doesn't work very well for nested text strings. So I removed
them completely in order to improve the title design on Android. We
should I general be very careful with line heights especially on
Android devices.
Replaces: https://github.com/kiwicom/react-native-app/pull/400
@tbergq Please check it if everything is still alright (I don't care about line heights in Zeplin).
=> HotelTitle: remove line heights to allow free text expansion

app/hotels/src/singleHotel/roomList/RoomRowTitle.js, app/shared/src/icons/TextIcon.js
There are obvious limitations for our 'Text' component. We need to nest
Texts because of container behaviour but in this case we cannot affect
vertical position of this nested text. All other style properties seems
to be OK. For this reason we should thing about future designs without
multiple text styles in one row.
See: https://facebook.github.io/react-native/docs/text.html#containers
Closes: https://github.com/kiwicom/react-native-app/issues/371
=> RoomRowTitle: fix 'RoomSize' component wrapping using &nbsp;

app/hotels/src/singleHotel/header/__tests__/__snapshots__/Rating.test.js.snap, app/playground/Playground.js, app/shared/src/Text.js, app/shared/src/__tests__/Text.test.js, app/shared/src/__tests__/__snapshots__/Text.test.js.snap, app/shared/src/errors/__tests__/__snapshots__/GeneralError.test.js.snap, app/shared/src/errors/__tests__/__snapshots__/PartialFailure.test.js.snap
Now I probably finally understand how does it work. Our default style
must be applied on the root (top) Text component only and inner deeply
nested components are inheriting previous styles only if their style is
undefined... :)
@tbergq Please also try your use-case. I rethought the internal implementation completely so now it behaves the same as RN implementation and it should just work. (I also don't know how to unit test this style changes on state change)
=> Text: improve styles inheritance to be RN compatible

.eslintrc.js, app/hotels/src/allHotels/searchForm/locationPicker/LocationPickerScreen.js, app/hotels/src/singleHotel/hotelInformation/location/Location.js, app/shared/src/forms/DatePicker.js, package.json, yarn.lock
Rule 'no-inline-styles' now throws warnings into console and we should
continuously fixing it (and change this rule to throw the errors).
See: https://github.com/Intellicode/eslint-plugin-react-native
=> Eslint: add 'react-native' rules

app/translations/src/DummyTranslation.js, app/translations/src/Translation.js, app/translations/src/TranslationFragment.js, app/translations/src/__tests__/TranslationFragment.test.js, app/translations/src/__tests__/__snapshots__/TranslationFragment.test.js.snap, app/translations/src/transformations/CaseTransform.js, app/translations/src/transformations/__tests__/CaseTransform.test.js
This props was used only in Translation component but it should be used
everywhere. Moreover the TranslationFragment should pass all props down.
=> Translations: fix transformation prop propagation

.build/package.json, app/hotels/package.json, package.json, yarn.lock
This fixes yellow boxes (bug in RN release - see https://github.com/facebook/react-native/issues/18175) as well as broken maps.
=> Dependencies: upgrade React Native to the ^0.54.0 version

app/shared/src/ReadMore.js, app/shared/src/Touchable.js, app/shared/src/__tests__/Touchable.ripple.test.js, app/shared/src/__tests__/__snapshots__/Touchable.ripple.test.js.snap
Android ripple effect is not always the best solution especially for
small button links. This new option will disable it:
```js
<Touchable noRipple={true}> ... </Touchable>
```
It should be used only rarely when it's appropriate or required.
=> ReadMore: disable ripple effect for link buttons

app/hotels/src/filter/stars/StarsFilter.js, app/translations/src/TranslationFragment.js, app/translations/src/__tests__/TranslationFragment.test.js, app/translations/src/__tests__/__snapshots__/TranslationFragment.test.js.snap
TranslationFragment passed all props into children except children
itself (to prevent children duplication). However this means that it was
not possible to deeply nest TranslationFragment components but we are
doing it in our code. This change fixes it.
=> Translations: fix propagation of props into 'TranslationFragment' children

app/navigation/package.json, yarn.lock
@tbergq Please test it. I didn't notice a single problem.
=> Dependencies: upgrade React Navigation to the latest version (^1.5.11)

app/MMB/src/HelpSubmenu.js, app/MMB/src/MainMenu.js, app/MMB/src/OtherSubmenu.js, app/MMB/src/components/menu/MenuItem.js, app/MMB/src/navigation/MMBListScreen.js, app/MMB/src/navigation/MMBScreen.js, app/MMB/src/navigation/NavigationStack.js, app/localization/src/DefaultVocabulary.js, app/navigation/types/Navigation.js
It behaves differently on mobile and tablet: mobile always open a new
stack but tablet only changes the container content. This makes it quite
challenging because tablet have to change the title as well as
sometimes allow to open new scene in stack (for map for example).
=> MMB: create PoC of the navigation

app/MMB/src/appRegistry/ManageMyBookingPackage.js, app/MMB/src/components/Layout.js, app/MMB/src/navigation/MMBScreen.js, app/hotels/src/appRegistry/RootComponent.js, app/hotels/src/map/allHotels/AllHotelsMap.js, app/hotels/src/map/allHotels/HotelSwipeList.js, app/hotels/src/map/singleHotel/BottomSheet.js, app/hotels/src/navigation/allHotels/AllHotelsNavigationScreen.js, app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/header/Header.js, app/hotels/src/singleHotel/hotelInformation/HotelInformation.js, app/hotels/src/singleHotel/hotelInformation/description/Description.js, app/hotels/src/singleHotel/roomList/RoomRow.js, app/shared/src/popup/Popup.js, app/shared/src/view/AdaptableLayout.js, app/shared/src/view/__tests__/AdaptableLayout.narrow.test.js, app/shared/src/view/__tests__/AdaptableLayout.test.js, app/shared/src/view/__tests__/AdaptableLayout.wide.test.js, app/shared/src/view/__tests__/__snapshots__/AdaptableLayout.narrow.test.js.snap, app/shared/src/view/__tests__/__snapshots__/AdaptableLayout.test.js.snap, app/shared/src/view/__tests__/__snapshots__/AdaptableLayout.wide.test.js.snap
I discovered an error in our MMB where AdaptableLayout didn't work
because we didn't set it in the right context. So I refactored it
completely in order to throw appropriate error (so it should never
happen again). Now it's necessary to use Provider-Consumer combo similar
to the React context API.
=> Refactor AdaptableLayout component

app/MMB/src/Layout.js
Basically right menu stops at 50% if expanding it to 520pt looks weird.
Closes: https://github.com/kiwicom/mobile/issues/520
=> MMB: update Layout responsivity for tablet in portrait mode

app/shared/package.json, yarn.lock
One at the time. It should be without BC breaks but it's a major upgrade.
=> Dependencies: upgrade 'react-native-modal' to the latest version

ios/RNKiwiMobile/RNKiwiConstants.h, ios/RNKiwiMobile/RNKiwiConstants.m, ios/RNKiwiMobile/RNKiwiMobile.h, ios/RNKiwiMobile/RNKiwiOptions.h, ios/RNKiwiMobile/RNKiwiSharedBridge.h, ios/RNKiwiMobile/RNKiwiSharedBridge.m, ios/RNKiwiMobile/RNKiwiViewController.m, ios/RNNativePlayground/ViewController.m, ios/reactNativeApp.xcodeproj/project.pbxproj
This pull request targets my `work in progress` branch (that is subject to another PR). Until it gets merged to master, this pull request should not be merged.
==
This pull request implements shared bridge to improve startup of our iOS applications. It introduces singleton class, called `RNKiwiSharedBridge` that holds all the bridges created for bundle URLs. 
Since we haven't settled yet whether to go with multiple bundles (and bridges) or single bundle (and multiple components), this PR supports both use cases. 
I believe that even if we settle on a single bundle, the current implementation that uses NSDictionary is still reasonable given that the method signature is `bridgeForBundleURL` and assumes we accept returning multiple bridges.
Now, how to load bridge upfront to result from …
=> Shared bridge

.flowconfig, app/shared/index.js, app/shared/src/PlatformStyleSheet.js, app/shared/types/Styles.js
It returned 'any' because of changed Relay internal structure. Don't be
scared by the weird names - I didn't find a better way how to do it. The
good thing is that it will handle much more. For example it will not
allow you to do this because it's invalid:
```
{
fontWeight: 500,
}
```
=> Fix Flow 'StylePropType'

app/shared/src/WithStorage.js, app/shared/src/__tests__/WithStorage.test.js
Sometimes the with storage warning would create a console.warn.
This was because we tried to to `JSON.parse(initialValue)` which was a parsed value and it would cause an unhandled promise rejection
=> Shared: Fix wrong usage of fallback value in WithStorage

packages/localization/src/CancellableTranslation.js, packages/localization/src/Translation.js, packages/localization/src/__tests__/Translation.test.js
Sometimes we get warning, can't call set state on unmounted component.
This happens when we leave a screen before all translations promises has resolved.
Making the promise cancellable should remove this warning.
=> Localization: Make translation promise cancellable

app/profile/components/authentication/EmailLoginForm.js, app/profile/index.js
Basically when debugging on device, after login, I had to shake device and reload to be able to navigate to mmb tab. Keyboard was on top of the tabs, and could not be closed.
=> Profile: Close keyboard when submitting login form

app/MMB/src/navigation/DetailShareButton.js, app/MMB/src/scenes/tripServices/ParkingMenuItem.js, app/core/config/NativeModulesMocks/RNDeviceInfo.js, ios/RNModules/RNDeviceInfo/RNDeviceInfo/RNDeviceInfo.m, packages/localization/index.js, packages/localization/src/DateFormatter.js, packages/localization/src/GetDeviceLocale.js, packages/relay/src/Environment.js, packages/shared/src/forms/datePicker/DatePicker.ios.js
Related to: #738 
Currently `GetDeviceLocale` always will return object:
```
{
Format: {
Underscored: 'en_US',
Dashed: 'en-US',
},
Language: 'en',
Territory: 'US',
},
```
where `Format.Underscored` and `Format.Dashed` are a combination of `Language` and `Territory`. In that way we are able to avoid appending unnecessary `calendar=gregorian`.
=> Avoid appending calendar in device info locale

packages/localization/src/DateFormatter.js, packages/localization/src/DateUtils.js
I think most our our current date problems is with formatting and timeZones, I will add a possibility to change time-zone for formatting. 
This makes sense to me, we can adjust for local timezone where needed, and our graphql returns timezone on locations, so we can also use that were it makes sense.
=> Localization: DateFormatter allow timeZone adjustment

packages/shared/src/popup/Popup.js
Note: For some reason this does not work for `StarsFilter` though the code is the same as for the rest of the filters 🤷‍♂️ 
I want to see if this issue persist after we upgrade `react-navigation`
=> Shared: Add safe area view to Popup component

app/MMB/src/navigation/ListScreen.js, app/MMB/src/navigation/NavigationStack.js, app/core/src/navigation/index.js, app/core/src/screens/MMBPackageWrapper.js, app/hotels/src/navigation/allHotels/GuestsModalScreen.js, app/hotels/src/navigation/allHotels/LocationPickerScreen.js, app/hotels/src/navigation/allHotels/__tests__/AllHotelsNavigationScreen.test.js, app/hotels/src/navigation/allHotels/__tests__/GuestsModalScreen.test.js, index.js, packages/navigation/package.json, packages/navigation/types/Navigation.js, yarn.lock
Closes #861.
Got two warnings (one ignored):
- https://reactnavigation.org/docs/en/common-mistakes.html <-- Ignored due our architecture with package and stack (to include in native app). We can review it later
- ~`react-navigation-props-mapper` gives a warning if used in stateless components (I removed it from MMB for now <-- I do not see is used there?). Question, can we remove it entirely? I do not see a huge benefit on using this dependency (we are using `navigate.state.params` in different places anyway). CC @tbergq~ Solved.
=> chore: Update to react-navigation 2.x.x.

.eslintignore, .gitignore, app/core/config/NativeModulesMocks/RNKiwiGestureController.js, packages/shared/src/WithNativeNavigation.js, packages/shared/src/__tests__/WithNativeNavigation.test.js
=> fix: Do not allow swipe back on iOS modals

app/MMB/src/components/MissingInformation.js, app/MMB/src/scenes/FlightServices.js, app/MMB/src/scenes/Other.js, app/MMB/src/scenes/flightServices/FlightServicesMenuGroup.js, app/MMB/src/scenes/help/index.js, app/MMB/src/scenes/list/cityImage/CityImageContainer.js, app/MMB/src/scenes/passenger/baggage/BaggageGroupButton.js, app/MMB/src/scenes/tickets/ETicket.js, app/MMB/src/scenes/tickets/boardingPasses/DownloadButton.js, app/MMB/src/scenes/timeline/events/DownloadBoardingPassTimelineEvent.js, app/MMB/src/scenes/timeline/events/DownloadETicketTimelineEvent.js, app/MMB/src/scenes/timeline/events/DownloadInvoiceTimelineEvent.js, app/MMB/src/scenes/timeline/events/components/ExploreAirportButton.js, app/MMB/src/scenes/travelDocument/menuItem/TravelDocumentPassengerMenuItem.js, app/MMB/src/scenes/tripServices/TripServices.js, app/MMB/src/scenes/tripServices/insurance/InsuranceOverviewScene.js, app/MMB/src/scenes/tripServices/insurance/menuItem/PassengerInsuranceMenuItem.js, app/core/src/screens/homepage/Homepage.js, app/hotels/src/navigation/allHotels/AllHotelsNavigationScreen.js, app/hotels/src/navigation/allHotelsMap/AllHotelsMapNavigationScreen.js, app/hotels/src/navigation/singleHotel/AdditionalPropsInjector.js, app/hotels/src/navigation/singleHotel/SingleHotelNavigationScreen.js, packages/navigation/package.json, packages/navigation/types/Navigation.js, packages/playground/src/PlaygroundList.js, yarn.lock
Fixes #898.
We did some investigation: https://snack.expo.io/SyECyLk4Q.
Therefore, we do not need `key` anymore to avoid pushing a screen twice. Using `navigate` is enough.
=> New types for react-navigation 2

app/MMB/index.js, app/MMB/src/context/WalletContext.js, app/MMB/src/context/__tests__/WalletContext.test.js, app/MMB/src/navigation/AppleWalletScreen.js, app/MMB/src/scenes/appleWallet/__generated__/WalletContent.graphql.js, app/MMB/src/scenes/tickets/__generated__/TicketRefetchQuery.graphql.js, app/MMB/src/scenes/tickets/__generated__/TicketSceneQuery.graphql.js, app/MMB/src/scenes/tickets/boardingPasses/FlightFromTo.js, app/MMB/src/scenes/tickets/boardingPasses/__generated__/FlightFromTo.graphql.js, app/MMB/src/scenes/tickets/boardingPasses/appleWallet/AppleWallet.js, app/MMB/src/scenes/tickets/boardingPasses/appleWallet/AppleWalletPassenger.js, app/MMB/src/scenes/tickets/boardingPasses/appleWallet/__generated__/AppleWalletPassenger.graphql.js
I considered two approaches to get data for the apple wallet screen. 
A: Use query renderer
• I would have to pass legId and passengerId the new screen
• Query the booking for all legs, loop all legs to find my leg, loop pkpasses to find my passenger
• This does not sound optimal
B: The chosen approach. 
• Prepare data in context and set the selected one when clicking on the passenger
• I would then be able to get all needed data on the apple wallet screen from the context through the selectedSegment. 
• I do have to prop drill legId down to the click handler, but I would have had to do that with approach A also. 
C: Could be an approach I did not consider, so please let me know if you see another way 😄
=> MMB: Prepare data for apple wallet screen

packages/navigation/index.js
Removes some warnings in the console
There still is this warning concerning navigators though: 
```
You should only render one navigator explicitly in your app, and other navigators should by rendered by including them in that navigator. Full details at: https://reactnavigation.org/docs/common-mistakes.html#explicitly-rendering-more-than-one-navigator
```
=> Using createStackNavigator instead of deprecated StackNavigator

app/MMB/index.js, app/MMB/src/context/SplitNavigationContext.js, app/MMB/src/context/__tests__/SplitNavigationContext.test.js, app/MMB/src/navigation/DetailScreen.js, app/MMB/src/scenes/tripServices/hotelMenuItem/HotelMenuItem.js
This is necessary since switchNavigator unmounts MMB stack, meaning that activeComponentId is lost. Moving it to context will persist it, so we are at correct navigation on tablet when we close Hotels modal.
=> MMB: Move split screen navigation active id to context

app/MMB/src/scenes/tickets/TicketDeleteButton.js, app/MMB/src/scenes/tickets/__generated__/TicketRefetchQuery.graphql.js, app/MMB/src/scenes/tickets/__generated__/TicketSceneQuery.graphql.js, app/MMB/src/scenes/tickets/__tests__/TicketDeleteButton.test.js, app/MMB/src/scenes/tickets/boardingPasses/DownloadButton.js, app/MMB/src/scenes/tickets/boardingPasses/__generated__/DownloadButton.graphql.js, app/MMB/src/scenes/tickets/boardingPassesPdf/BoardingPassPdf.js, app/MMB/src/scenes/tickets/boardingPassesPdf/BoardingPassPdfScreen.js, app/MMB/src/scenes/tickets/boardingPassesPdf/__tests__/BoardingPassPdf.test.js, app/MMB/src/scenes/timeline/events/DownloadBoardingPassTimelineEvent.js
I was trying to re-add sharing functionality (which somehow has disappeared 🙈 ), and it seems the share extension has some problems with url encoded characters. So a little refactor of the filenames was needed. 
We will now store it like `/boardingPasses/bookingId/flightNumber.pdf`
=> MMB: Refactor boarding pass storage to use bookingId/flightNumber.pdf

app/native.js, ios/RNNativePlayground/ViewController.m
Small improvement:
* replace fixed dates for live dates
* ignore warnings in the playground come from `react-native-share` -> remove when v. 1.1.3 will be released
=> Use live dates instead of fixed

android/playground/build.gradle
Bug was introduced with CodePush.
=> Fix building Android Playground on Debug mode

rn-cli.config.js
This is happening because iOS references `package.json` as resource, as it needs to read code push version from there.
=> Fix: blackList package.json from iOS build folder

packages/localization/src/Translation.js, packages/localization/src/__tests__/__snapshots__/Translation.test.js.snap
=> Localization: have translation render null instead of string null when passThrough is undefined

app/hotels/src/HotelsContext.js, app/hotels/src/__tests__/HotelsContext.test.js, app/hotels/src/allHotels/HotelsPaginationContainer.js, app/hotels/src/allHotels/HotelsSearch.js, app/hotels/src/allHotels/NewAllHotels.js, app/hotels/src/allHotels/NewAllHotelsSearch.js, app/hotels/src/allHotels/Stay22HotelsSearch.js, app/hotels/src/allHotels/__tests__/Stay22HotelsSearch.test.js, app/hotels/src/appRegistry/NewHotelsStandalonePackage.js, app/hotels/src/appRegistry/RootComponent.js, app/hotels/src/appRegistry/SingleHotelStandalonePackage.js, app/hotels/src/components/CloseModal.js, app/hotels/src/filter/FilterStripe.js, app/hotels/src/navigation/allHotels/SearchResultsScreen.js, packages/relay/index.js, packages/relay/src/PrivateApiRenderer.js, packages/relay/src/PublicApiRenderer.js, packages/relay/src/QueryRenderer.js, packages/relay/src/__tests__/QueryRenderer.test.js, packages/relay/src/__tests__/__snapshots__/QueryRenderer.test.js.snap, packages/shared/src/offlineScreen/OfflineScreen.js, packages/shared/src/offlineScreen/__tests__/__snapshots__/OfflineScreen.test.js.snap
Some issues/discoveries
• We might need to render different offline screens (since close does not make sense for non modal screens)
• the fixed position close button needs to be rendered inside the queryrenderer, if not it will render on top of offline screen buttons, or be missing on other error screens. Meaning we will not be able to close the modal on errors, which is bad UX.
Therefore a renderOfflineScreen passing the retry functions was the best solution I found. Also passing the footer component is a result of the above. 
Let me know if you can think of any improvements.
=> Hotels: Show offline screen for all hotels search results screen

android/app/build.gradle, ios/reactNativeApp.xcodeproj/project.pbxproj
Fixes #1374.
This is a nasty workaround. We need to use `compile` instead of `implementation` or linking command will link it again.
Soon we can get rid of all of this when CLI is not preview here https://github.com/react-native-community/react-native-cli/pull/30 anymore.
=> Workaround for not linking CodePush on "app"

app/MMB/src/scenes/tripServices/insurance/insuranceOverviewScene/orderSummary/InsuranceRow.js, app/MMB/src/scenes/tripServices/insurance/insuranceOverviewScene/orderSummary/OrderSummary.js, app/MMB/src/scenes/tripServices/insurance/insuranceOverviewScene/orderSummary/__tests__/InsuranceRow.test.js, app/MMB/src/scenes/tripServices/insurance/insuranceSelectionScene/variantButtons/Price.js, app/hotels/src/allHotels/HotelTitle.js, app/hotels/src/filter/price/PriceFilter.js, app/hotels/src/filter/price/PricePopup.js, app/hotels/src/map/allHotels/HotelSwipeItem.js, app/hotels/src/map/allHotels/PriceMarker.js, app/hotels/src/map/hotelDetailPreview/HotelDetailPreview.js, app/hotels/src/map/singleHotel/AdditionalInfo.js, app/hotels/src/map/singleHotel/__generated__/AdditionalInfo.graphql.js, app/hotels/src/map/singleHotel/__generated__/SingleHotelMapScreenQuery.graphql.js, app/hotels/src/map/singleHotel/__generated__/Stay22SingleHotelMapScreenQuery.graphql.js, app/hotels/src/singleHotel/roomPicker/IncrementDecrement.js, app/hotels/src/singleHotel/roomPicker/SelectButton.js, app/hotels/src/singleHotel/summary/RoomSummary.js, packages/shared/src/Price.js, packages/shared/src/__tests__/Price.test.js
The motivation for this is to have the price component work with the eslint rule relay/unused-fields.
When we pass price as object, relay/unused-fields thinks we are not using amount and currency
=> Refactor price component to take amount and currency props

app/MMB/src/scenes/tickets/__tests__/__snapshots__/TicketDeleteButton.test.js.snap, packages/shared/src/icons/Icon.js, packages/shared/src/icons/__tests__/Icon.test.js, packages/shared/src/icons/__tests__/__snapshots__/Icon.test.js.snap
Some of our icons have a custom fontSize (not orbit sizes).
We need to override width, height and lineHeight also, better to do this in the Icon component than adding this style to very single component that overrides this style
=> Shared: Add fontSize prop for our icons with custom fontSize

scripts/configureApplication.js
And again, no need to change `code-push-target-version` since there is no change in how the bundle calls the native code.
The only change now lies within the published framework, which means iOS needs to pull latest release after this PR is merged, and it should work.
this is how it looks like for me after the patch:
=> Patch react-native RCTUtils.m to work with code-push

package.json, scripts/configureApplication.js
Mobile CI runs on lower versions of node, we need to upgrade image there first.
Added a log warning in configureApplication.js for lower versions of node
=> Remove node engine from package json

app/hotels/src/allHotels/HotelsPaginationContainer.js, app/hotels/src/allHotels/HotelsSearch.js, app/hotels/src/map/singleHotel/SingleMap.js, app/hotels/src/map/singleHotel/SingleMapQueryRenderer.js, app/hotels/src/singleHotel/HotelDetailScreen.js, app/hotels/src/singleHotel/SingleHotelSearch.js, packages/relay/index.js, packages/relay/src/PrivateApiRenderer.js, packages/relay/src/PublicApiRenderer.js, packages/relay/src/QueryRenderer.js, packages/relay/src/__tests__/QueryRenderer.test.js, packages/relay/src/__tests__/__snapshots__/QueryRenderer.test.js.snap
Replace footer with errorFooter.
Reconnect close modal components where they belong in component tree.
=> Relay: Refactor QueryRenderer to use props from kiwi package

packages/relay/src/Environment.js, packages/relay/src/PrivateApiRenderer.js, packages/relay/src/PrivateEnvironment.js, packages/relay/src/QueryRenderer.js, packages/relay/src/__tests__/QueryRenderer.test.js
We have different header keys for authorization, so we need to be able
to change this header value based on which query we are calling
=> Relay: Allow changing the authorization header key

app/hotels/src/allHotels/RenderSearchResults.js
If the iPad was opened in landscape mode, then flipped
the map would show underneath the list view.
This fixes this bug.
closes #1568
=> Hotels: Add onLayout event to RenderSearchResults

package.json, yarn.lock
It seems this is no longer needed.
The app runs just fine without it
=> Remove babel-core resolution

app/App.js, app/hotels/src/appRegistry/NewHotelsStandalonePackage.js, app/hotels/src/appRegistry/RootComponent.js, app/hotels/src/appRegistry/SingleHotelStandalonePackage.js, ios/RNNativePlayground/ViewController.m, packages/playground/src/Playground.js, packages/shared/src/popup/__tests__/ButtonPopup.test.js, packages/shared/src/view/DimensionsConsumer.js, packages/shared/src/view/DimensionsContext.js, packages/shared/src/view/DimensionsProvider.js, packages/shared/src/view/__tests__/AdaptableLayout.narrow.test.js, packages/shared/src/view/__tests__/AdaptableLayout.test.js, packages/shared/src/view/__tests__/AdaptableLayout.wide.test.js, packages/shared/src/view/__tests__/__snapshots__/AdaptableLayout.narrow.test.js.snap, packages/shared/src/view/__tests__/__snapshots__/AdaptableLayout.test.js.snap, packages/shared/src/view/__tests__/__snapshots__/AdaptableLayout.wide.test.js.snap
These dimensions was not used anyway. They were put into the context
then overwritten by the onLayout function triggering when the app started up
closes #1567
=> Remove usage of dimensions passed from native iOS app

packages/relay/src/PrivateApiRenderer.js
**PrivateApiRendererWithContext** as default export should take **authHeaderKey** as a prop and forward it to **PrivateApiRenderer** and _accessToken_ is optional since it is taken from context and not provided via props.
=> mobile-relay: Fixed props for PrivateApiRenderer

.build/package.json, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/RNKiwiActivity.kt, docs/common/changelog.md
React-Native has changed DatePickerDialogModule to only support FragmentActivity
https://github.com/facebook/react-native/pull/23371
=> Android: Change RNKiwiActivity to extend FragmentActivity

ios/RNKiwiMobile/AncillaryViewController.h, ios/RNKiwiMobile/AncillaryViewController.m, ios/RNKiwiMobile/RNKiwiMobile.h, ios/reactNativeApp.xcodeproj/project.pbxproj
This is remaining code for fast track ancillary.
iOS team wanted to have a clear view controller for ancillaries integration, that's why it doesn't have `RNKiwi` prefix.
=> Ancillaries: Added AncillaryViewController for integrating ancillaries

app/hotels/src/filter/stars/StarsPopup.js
This fixes MOBILE-4112.
This was also not rendered correctly on iOS: some separators would be rendered with bigger height than others. My interpretation of this issue is that `0.5` is not consistently rendered on different screens with different screen densities. Using `StyleSheet.hairlineWidth` fixes this issue as it's optimised to always be a round number of pixels
> This constant will always be a round number of pixels (so a line defined by it can look crisp) and will try to match the standard width of a thin line on the underlying platform
https://facebook.github.io/react-native/docs/stylesheet#hairlinewidth
=> Hotels: FIX height of separator in StarsPopup

app/hotels/src/singleHotel/summary/SummaryRow.js
This fixes https://github.com/kiwicom/mobile/issues/1607
The issue was that using the `withDimension` HOC meant using the dimensions of the device. On Tablet view, the RoomSummary component is displayed only on half the screen width while SummaryRow assumed there is the full width of the device to render the text. This caused the row to go out of the container if the name of the hotel room was too long on Tablet.
The SummaryRow component was refactored to use two onLayout event listeners so that both the width of the container of the row and the width of the price tag are computed, and the max width for text can be deduced from that.
=> Hotels: SummaryRow should use dynamic width to truncate text

android/app/src/main/java/com/reactnativeapp/MainActivity.java, app/hotels/src/allHotels/RenderSearchResults.js, app/hotels/src/navigation/allHotels/navigationOptions/NavigationOptions.js
The toast became visible above the header.
Changed marginTop to paddingTop to prevent this behaviour.
React-native-gesture-handler was not set up correctly, fix that also(in dev)
Note it will not work in production until we fix it in RNHotelsActivity.kt
and deploy a new framework
=> Shared: Fix android toast swipe

.jest.config.js, __mocks__/fileMock.js, app/ancillaryFactory/package.json, app/fastTrack/package.json, app/hotels/package.json, packages/orbit/package.json, packages/shared/package.json, yarn.lock
It was necessary to:
- add date-fns@1.30.1 as a dependency since it's become a peer dependency to Universal Components,
- stub .ttf font files as tests would fail otherwise; it's most likely because of the introduction of a ThemeProvider in Universal Components which explicitly imports the font files)
e2e tests passed on iPhone and iPad (couldn't get it to work on Android somehow)
tested manually on Android emulator
Fixes #1640
=> Upgrade @kiwicom/universal-components to v0.0.17

app/account/package.json, app/account/src/appRegistry/AccountSettings.js, app/core/src/navigation/stacks/ProfileStack.js, app/native.js, app/profile/index.js, app/profile/package.json, ios/RNNativePlayground/Base.lproj/Main.storyboard, ios/RNNativePlayground/ViewController.m, ios/reactNativeApp.xcodeproj/project.pbxproj, package.json, react-native.config.js, yarn.lock
Note that this is ok, but we should not yet tell native that
account is available.
If they try to access it in production it could crash.
We need to publish new code-push-target-version before it is safe to use
in production
=> playground-ios: Add account to playground app

.github/CODEOWNERS
This code goes into production, so it makes sense to have
review from someone on the android team
=> codeowners: Set Blackhex as codeowner of rnkiwimobile

e2e/config.json, package.json, yarn.lock
Major upgrade, but seems the only BC is dropping support
for iOS 9.X simulators
=> Upgrade detox

android/playground/src/main/AndroidManifest.xml, android/playground/src/main/java/com/kiwi/mobile/rnandroidplayground/AccountPriceAlertsActivity.kt, android/playground/src/main/java/com/kiwi/mobile/rnandroidplayground/AccountSettingsActivity.kt, android/playground/src/main/java/com/kiwi/mobile/rnandroidplayground/MainActivity.kt, android/playground/src/main/res/layout/activity_main.xml, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/account/RNAccountActivity.kt, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/account/RNAccountModule.kt, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/account/RNAccountPriceAlertsActivity.kt, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/account/RNAccountSettingsActivity.kt, app/account/index.js, app/account/src/TodoScreen.js, app/account/src/WithAccountStack.js, app/account/src/appRegistry/PriceAlerts.js, app/native.js, ios/RNNativePlayground/Base.lproj/Main.storyboard, ios/RNNativePlayground/ViewController.m
Note: I want to prepare Also price alerts. This way, the next time we increase the framework version, it should be possible for native to access and test the accounts screens and we can keep pushing new code with code-push. 
We should release yet a new version before going to production, since there is a risk that the user will see the `under development screen` if he visits the screen before the app has downloaded the new bundle from code-push
=> accounts: Prepare price alerts screen

ios/RNNativePlayground/Base.lproj/Main.storyboard
Account will run with native tabbar visible
Right now, rn screens render below the tabbar
This will help with the debugging
=> RNPlayground: add tabbar

.build/package.json, ios/Podfile.lock, ios/RNKiwiMobile/RNKiwiAccountUpdater.h, ios/RNKiwiMobile/RNKiwiAccountUpdater.m, ios/RNKiwiMobile/RNKiwiViewController.h, ios/RNKiwiMobile/RNKiwiViewController.m, ios/reactNativeApp.xcodeproj/project.pbxproj, package.json
Add RNKiwiAccountUpdater to expose `accountDeleted` method to JS. Add `didDeleteAccount` property to react (ha) to account deletion in iOS app.
=> accountDeleted method for iOS

android/playground/src/main/java/com/kiwi/mobile/rnandroidplayground/PlaygroundApplication.kt, android/rnkiwimobile/src/main/java/com/kiwi/rnkiwimobile/account/RNAccountModule.kt
Note that without #1720 bundle will not be loaded when you run `yarn android-playground`
=> Pass android bridge account function

packages/localization/src/GetDeviceLocale.android.js
Android native module only return Locale like `en-GB`
So we have to parse this in JS for it to work as it does on iOS
=> Fix DeviceLocale for android

e2e/.eslintrc, e2e/hotels/hotelDetails/notEnoughBeds.spec.js, packages/localization/src/vocabularies/Hotels.js
This commit also silences ESLint warnings in `e2e/` folder for the rule `adeira/valid-test-folder` as that folder only contains tests: it would be redundant to create a `__tests__/` folder for each subfolder in `e2e/`.
=> fix(localization): Fix typo in Hotels' translations
